/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

// Not exported
@interface _UIAutologgingDeallocSentinel : NSObject
{
    _Bool _called;
    NSString *_message;
}

@property(nonatomic) _Bool called; // @synthesize called=_called;
@property(retain, nonatomic) NSString *message; // @synthesize message=_message;
- (void)dealloc;

@end

