/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <UIKit/UIStatusBarNewUIForegroundStyleAttributes.h>

@interface UIStatusBarLockScreenForegroundStyleAttributes : UIStatusBarNewUIForegroundStyleAttributes
{
}

- (struct CGPoint)positionForMoonMaskInBounds:(struct CGRect)arg1;
- (float)sizeForMoonMaskVisible:(BOOL)arg1;
- (id)makeTextFontForStyle:(int)arg1;
- (struct UIEdgeInsets)edgeInsetsForBluetoothBatteryInsides;
- (struct UIEdgeInsets)edgeInsetsForBatteryInsides;
- (int)activityIndicatorStyleWithSyncActivity:(BOOL)arg1;
- (id)expandedNameForImageName:(id)arg1;

@end

