//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_xpc_object>;

@interface AXUIServiceContext : NSObject
{
    id <AXUIService> _service;
    NSObject<OS_xpc_object> *_connection;
    unsigned int _clientIdentifier;
}

@property(nonatomic) unsigned int clientIdentifier; // @synthesize clientIdentifier=_clientIdentifier;
@property(retain, nonatomic) NSObject<OS_xpc_object> *connection; // @synthesize connection=_connection;
@property(retain, nonatomic) id <AXUIService> service; // @synthesize service=_service;
- (void)dealloc;

@end

