//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <iTunesStoreUI/SUDownloadCellConfiguration.h>

@interface SUDownloadGridCellConfiguration : SUDownloadCellConfiguration
{
}

+ (id)copyDefaultContext;
+ (float)rowHeightForContext:(id)arg1 representedObject:(id)arg2;
- (struct CGRect)frameForProgressBar:(id)arg1;
- (void)reloadLayoutInformation;
- (struct CGRect)frameForTitle;

@end

