/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "MFMessageDataConsumerFactory-Protocol.h"

@class Message, MessageLibrary;

@interface _MFDALibraryConsumerFactory : NSObject <MFMessageDataConsumerFactory>
{
    MessageLibrary *_library;
    Message *_message;
}

@property(retain, nonatomic) Message *message; // @synthesize message=_message;
@property(retain, nonatomic) MessageLibrary *library; // @synthesize library=_library;
- (void)dealloc;
- (id)dataConsumerForPart:(id)arg1;

@end

