/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSDictionary;

@interface MessageWriter : NSObject
{
    Class _messageClassToInstantiate;
    unsigned int _allows8BitMimeParts:1;
    unsigned int _allowsBinaryMimeParts:1;
    unsigned int _writeSizeDispositionParameter:1;
    unsigned int _allowsQuotedPrintable:1;
    id _delegate;
    NSDictionary *_compositionSpecification;
}

@property(readonly, nonatomic) NSDictionary *compositionSpecification; // @synthesize compositionSpecification=_compositionSpecification;
@property(nonatomic) id delegate; // @synthesize delegate=_delegate;
- (void)setMessageClassToInstantiate:(Class)arg1;
- (void)setWriteSizeDispositionParameter:(BOOL)arg1;
- (void)setAllowsQuotedPrintable:(BOOL)arg1;
- (BOOL)allowsQuotedPrintable;
- (void)setAllowsBinaryMimeParts:(BOOL)arg1;
- (BOOL)allowsBinaryMimeParts;
- (void)setAllows8BitMimeParts:(BOOL)arg1;
- (BOOL)allows8BitMimeParts;
- (id)createMessageWithHtmlString:(id)arg1 attachments:(id)arg2 headers:(id)arg3;
- (id)createMessageWithHtmlString:(id)arg1 plainTextAlternative:(id)arg2 otherHtmlStringsAndAttachments:(id)arg3 charsets:(id)arg4 headers:(id)arg5;
- (id)createMessageWithHtmlString:(id)arg1 plainTextAlternative:(id)arg2 otherHtmlStringsAndAttachments:(id)arg3 headers:(id)arg4;
- (id)createMessageWithPlainTextDocumentsAndAttachments:(id)arg1 headers:(id)arg2;
- (id)createMessageWithString:(id)arg1 headers:(id)arg2;
- (void)appendDataForMimePart:(id)arg1 toData:(id)arg2 withPartData:(id)arg3;
- (void)dealloc;
- (id)initWithCompositionSpecification:(id)arg1;
- (id)init;

@end

