/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <StoreKitUI/SKUIPageComponent.h>

@class NSString, SKUIArtworkList;

@interface SKUIMediaComponent : SKUIPageComponent
{
    NSString *_accessibilityLabel;
    int _alignment;
    long long _mediaIdentifier;
    int _mediaType;
    NSString *_mediaURLString;
    SKUIArtworkList *_thumbnailArtworkList;
    NSString *_title;
    float _titleFontSize;
    int _titleFontWeight;
}

@property(readonly, nonatomic) int titleFontWeight; // @synthesize titleFontWeight=_titleFontWeight;
@property(readonly, nonatomic) float titleFontSize; // @synthesize titleFontSize=_titleFontSize;
@property(readonly, nonatomic) NSString *title; // @synthesize title=_title;
@property(readonly, nonatomic) SKUIArtworkList *thumbnailArtworkList; // @synthesize thumbnailArtworkList=_thumbnailArtworkList;
@property(readonly, nonatomic) NSString *mediaURLString; // @synthesize mediaURLString=_mediaURLString;
@property(readonly, nonatomic) int mediaType; // @synthesize mediaType=_mediaType;
@property(readonly, nonatomic) long long mediaIdentifier; // @synthesize mediaIdentifier=_mediaIdentifier;
@property(readonly, nonatomic) int alignment; // @synthesize alignment=_alignment;
@property(readonly, nonatomic) NSString *accessibilityLabel; // @synthesize accessibilityLabel=_accessibilityLabel;
- (void).cxx_destruct;
- (id)metricsElementName;
- (int)componentType;
- (id)bestThumbnailArtwork;
- (id)initWithCustomPageContext:(id)arg1;
- (id)initWithArtwork:(id)arg1;

@end

