//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class HKHealthService;

@protocol HDDaemonDeviceManager <NSObject>
- (void)disconnectHealthDevice:(unsigned int)arg1;
- (unsigned int)connectHealthDevice:(HKHealthService *)arg1 healthDatabase:(id <HDHealthDatabase>)arg2 sessionHandler:(void (^)(unsigned int, int, BOOL, NSError *))arg3 error:(id *)arg4;
@end

