//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SKUISearchFieldDelegate.h"

@class SKUIClientContext, SKUISearchFieldController, UIViewController;

@interface SKUIIPadSearchController : NSObject <SKUISearchFieldDelegate>
{
    SKUIClientContext *_clientContext;
    UIViewController *_parentViewController;
    SKUISearchFieldController *_searchFieldController;
}

@property(readonly, nonatomic) UIViewController *parentViewController; // @synthesize parentViewController=_parentViewController;
@property(retain, nonatomic) SKUIClientContext *clientContext; // @synthesize clientContext=_clientContext;
- (void).cxx_destruct;
- (void)_searchFieldController:(id)arg1 requestSearchWithURL:(id)arg2 orSearchTerm:(id)arg3 andMetricsEvent:(id)arg4;
- (id)_sharedResultsViewController;
- (id)_searchFieldController;
- (id)_existingSharedResultsViewController;
- (void)_termDidChangeNotification:(id)arg1;
- (BOOL)searchFieldControllerShouldBeginEditing:(id)arg1;
- (void)searchFieldController:(id)arg1 requestSearchWithSearchTerm:(id)arg2 metricsEvent:(id)arg3;
- (void)searchFieldController:(id)arg1 requestSearchWithURL:(id)arg2 metricsEvent:(id)arg3;
- (void)setNumberOfSearchResults:(int)arg1;
- (void)reloadSearchField;
- (id)newSearchFieldBarItem;
- (void)setSearchFieldText:(id)arg1;
- (void)setSearchFieldPlaceholderText:(id)arg1;
@property(readonly, nonatomic) SKUISearchFieldController *searchFieldController;
- (void)dealloc;
- (id)initWithParentViewController:(id)arg1;

@end

