//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <StoreKitUI/SKUIPageComponent.h>

@class SKUICountdown;

@interface SKUICountdownComponent : SKUIPageComponent
{
    SKUICountdown *_countdown;
}

@property(retain, nonatomic) SKUICountdown *countdown; // @synthesize countdown=_countdown;
- (void).cxx_destruct;
- (int)componentType;
- (id)initWithCustomPageContext:(id)arg1;

@end

