/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <StoreKitUI/SKUIPageComponent.h>

@interface SKUIAccountButtonsComponent : SKUIPageComponent
{
    _Bool _hidesTermsAndConditions;
}

@property(nonatomic) _Bool hidesTermsAndConditions; // @synthesize hidesTermsAndConditions=_hidesTermsAndConditions;
- (long long)componentType;
- (id)initWithCustomPageContext:(id)arg1;

@end

