//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, RUAddSeedViewController;

@protocol RUAddSeedViewControllerDelegate <NSObject>

@optional
- (void)addSeedViewControllerDidCancel:(RUAddSeedViewController *)arg1;
- (void)addSeedViewController:(RUAddSeedViewController *)arg1 didSelectStation:(NSDictionary *)arg2;
@end

