/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <ImageCapture/ICCameraFolder.h>

@interface ExFATCameraFolder : ICCameraFolder
{
    void *_exFATCameraFolderProperties;
}

- (_Bool)deleteItemFromCamera:(id)arg1;
- (void)enumerateContent;
@property(readonly) long long fsSize;
@property(readonly) struct timespec fsModificationTime;
@property(readonly) struct timespec fsCreationTime;
@property(readonly) id object;
- (void)finalize;
- (void)dealloc;
- (id)initWithName:(id)arg1 parentFolder:(id)arg2 device:(id)arg3 object:(id)arg4 fsCreationTime:(struct timespec)arg5 fsModificationTime:(struct timespec)arg6 fsSize:(long long)arg7;

@end

