//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface HKBloodTypeObject : NSObject
{
    int _bloodType;
}

@property(readonly) int bloodType; // @synthesize bloodType=_bloodType;
- (id)_initWithBloodType:(int)arg1;

@end

