/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <AVFoundation/AVAssetInspector.h>

@class NSArray, NSURL;

@interface AVFigAssetInspector : AVAssetInspector
{
    struct OpaqueFigAsset *_figAsset;
    struct OpaqueFigFormatReader *_formatReader;
    BOOL didCheckForSaveRestriction;
    BOOL hasSaveRestriction;
}

- (id)initWithFigAsset:(struct OpaqueFigAsset *)arg1;
- (void)dealloc;
- (void)finalize;
- (BOOL)isEqual:(id)arg1;
- (unsigned int)hash;
@property(readonly, nonatomic, getter=_figAsset) struct OpaqueFigAsset *figAsset;
- (struct OpaqueFigFormatReader *)_formatReader;
- (void *)_valueAsCFTypeForProperty:(struct __CFString *)arg1;
- (CDStruct_1b6d18a9)duration;
- (float)preferredRate;
- (float)preferredVolume;
- (struct CGAffineTransform)preferredTransform;
- (struct CGSize)naturalSize;
- (int)naturalTimeScale;
- (BOOL)providesPreciseDurationAndTiming;
- (long)trackCount;
- (id)alternateTrackGroups;
- (id)trackReferences;
- (id)mediaSelectionGroups;
- (id)creationDate;
- (id)lyrics;
- (id)commonMetadata;
- (id)availableMetadataFormats;
- (id)metadataForFormat:(id)arg1;
- (BOOL)_hasQTSaveRestriction;
- (BOOL)isExportable;
- (BOOL)isReadable;
- (BOOL)isComposable;
@property(readonly, nonatomic) NSArray *chapterGroupInfo;
@property(readonly, nonatomic) NSURL *URL;
@property(readonly, nonatomic) NSURL *resolvedURL;
@property(readonly, nonatomic) BOOL hasProtectedContent;

@end

