/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iLifeSlideshow/MPLayer.h>

@class MCContainerParallelizer, NSArray;

@interface MPLayerAnimatedSet : MPLayer
{
    NSArray *_animatedSets;
    MCContainerParallelizer *_layerParallelizer;
}

- (void)setAudioPlaylist:(id)arg1;
- (void)moveEffectContainersFromIndices:(id)arg1 toIndex:(long long)arg2;
- (void)removeEffectContainersAtIndices:(id)arg1;
- (void)insertEffectContainers:(id)arg1 atIndex:(long long)arg2;
- (void)setAnimatedSets:(id)arg1;
- (id)animatedSets;
- (void)dealloc;
- (void)finalize;
- (id)description;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)init;

@end

