//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <ITMLKit/IKViewElement.h>

@class NSString, NSURL;

@interface IKAssetElement : IKViewElement
{
    BOOL _infiniteDuration;
}

+ (BOOL)shouldParseChildDOMElements;
@property(readonly, nonatomic, getter=isInfiniteDuration) BOOL infiniteDuration; // @synthesize infiniteDuration=_infiniteDuration;
@property(readonly, retain, nonatomic) NSString *serviceID;
@property(readonly, retain, nonatomic) NSString *contentID;
@property(readonly, retain, nonatomic) NSString *bookmarkID;
@property(readonly, retain, nonatomic) NSString *adamID;
@property(readonly, retain, nonatomic) NSString *actionParams;
- (BOOL)infiniteDuration;
@property(readonly, nonatomic) int keyDelivery;
@property(readonly, nonatomic) int type;
@property(readonly, retain, nonatomic) NSURL *url;

@end

