//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CLGeocoder, NSArray, NSMutableDictionary, NSSet, PLMomentNodeCache;

@interface PLMomentClustering : NSObject
{
    BOOL _dirty;
    BOOL _accumulatesSmallClusters;
    BOOL _spatialJoinsAdjacentClusters;
    CDUnknownBlockType _progressBlock;
    NSArray *_clusters;
    NSSet *_insertedClusters;
    NSSet *_updatedClusters;
    NSSet *_deletedClusters;
    unsigned int _accumulationSize;
    unsigned int __minimumNumberOfNodes;
    unsigned int __numberOfVisitedNodes;
    unsigned int __totalNumberOfNodes;
    PLMomentNodeCache *__nodeCache;
    CLGeocoder *__geocoder;
    NSMutableDictionary *__markedNodesByObjectID;
    NSMutableDictionary *__clustersByObjectID;
    NSMutableDictionary *__clustersByNodeObjectID;
    double _sigma;
    double _theta;
    double _accumulationTimeInterval;
    double _accumulationJoinThreshold;
    double _accumulationRejectionThreshold;
    double _accumulationRejectionTimeInterval;
    double _spatialJoinTimeInterval;
    double _spatialJoinThreshold;
}

+ (double)maximumClusterTime;
@property(readonly, nonatomic) NSMutableDictionary *_clustersByNodeObjectID; // @synthesize _clustersByNodeObjectID=__clustersByNodeObjectID;
@property(readonly, nonatomic) NSMutableDictionary *_clustersByObjectID; // @synthesize _clustersByObjectID=__clustersByObjectID;
@property(readonly, nonatomic) NSMutableDictionary *_markedNodesByObjectID; // @synthesize _markedNodesByObjectID=__markedNodesByObjectID;
@property(readonly, nonatomic) CLGeocoder *_geocoder; // @synthesize _geocoder=__geocoder;
@property(readonly, nonatomic) PLMomentNodeCache *_nodeCache; // @synthesize _nodeCache=__nodeCache;
@property(nonatomic, setter=_setTotalNumberOfNodes:) unsigned int _totalNumberOfNodes; // @synthesize _totalNumberOfNodes=__totalNumberOfNodes;
@property(nonatomic, setter=_setNumberOfVisitedNodes:) unsigned int _numberOfVisitedNodes; // @synthesize _numberOfVisitedNodes=__numberOfVisitedNodes;
@property(nonatomic, setter=_setMinimumNumberOfNodes:) unsigned int _minimumNumberOfNodes; // @synthesize _minimumNumberOfNodes=__minimumNumberOfNodes;
@property(nonatomic) double spatialJoinThreshold; // @synthesize spatialJoinThreshold=_spatialJoinThreshold;
@property(nonatomic) double spatialJoinTimeInterval; // @synthesize spatialJoinTimeInterval=_spatialJoinTimeInterval;
@property(nonatomic) BOOL spatialJoinsAdjacentClusters; // @synthesize spatialJoinsAdjacentClusters=_spatialJoinsAdjacentClusters;
@property(nonatomic) double accumulationRejectionTimeInterval; // @synthesize accumulationRejectionTimeInterval=_accumulationRejectionTimeInterval;
@property(nonatomic) double accumulationRejectionThreshold; // @synthesize accumulationRejectionThreshold=_accumulationRejectionThreshold;
@property(nonatomic) double accumulationJoinThreshold; // @synthesize accumulationJoinThreshold=_accumulationJoinThreshold;
@property(nonatomic) double accumulationTimeInterval; // @synthesize accumulationTimeInterval=_accumulationTimeInterval;
@property(nonatomic) unsigned int accumulationSize; // @synthesize accumulationSize=_accumulationSize;
@property(nonatomic) BOOL accumulatesSmallClusters; // @synthesize accumulatesSmallClusters=_accumulatesSmallClusters;
@property(nonatomic, getter=isDirty, setter=_setDirty:) BOOL dirty; // @synthesize dirty=_dirty;
@property(nonatomic) double theta; // @synthesize theta=_theta;
@property(nonatomic) double sigma; // @synthesize sigma=_sigma;
- (void)_setDeletedClusters:(id)arg1;
@property(copy, nonatomic) NSSet *deletedClusters; // @synthesize deletedClusters=_deletedClusters;
- (void)_setUpdatedClusters:(id)arg1;
@property(copy, nonatomic) NSSet *updatedClusters; // @synthesize updatedClusters=_updatedClusters;
- (void)_setInsertedClusters:(id)arg1;
@property(copy, nonatomic) NSSet *insertedClusters; // @synthesize insertedClusters=_insertedClusters;
- (void)_setClusters:(id)arg1;
@property(copy, nonatomic) NSArray *clusters; // @synthesize clusters=_clusters;
@property(copy, nonatomic) CDUnknownBlockType progressBlock; // @synthesize progressBlock=_progressBlock;
- (void)markNodeForDiagnosis:(id)arg1;
@property(readonly, nonatomic) BOOL hasMarkedNodes;
- (id)spatialJoinClustersFromClusters:(id)arg1;
- (id)accumulateSmallClustersFromClusters:(id)arg1;
- (id)neighborsOfNode:(id)arg1;
- (id)temporalSnapshotOfNode:(id)arg1 withRange:(double)arg2;
- (id)clustersWithNodes:(id)arg1 sigma:(double)arg2 theta:(double)arg3;
- (void)generateClustersForAssets:(id)arg1 withCompletionBlock:(CDUnknownBlockType)arg2;
- (id)generateClustersForAssets:(id)arg1;
- (void)dealloc;
- (id)initWithManagedMoments:(id)arg1;
- (id)init;
- (void)_commonPLMomentClusteringManagerInitialization;

@end

