/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "GEOResourceManifestTileGroupObserver-Protocol.h"

@class NSMapTable, _VKLocalIconAtlas;

// Not exported
@interface VKIconManager : NSObject <GEOResourceManifestTileGroupObserver>
{
    NSMapTable *_defaultAtlases;
    NSMapTable *_regionalAtlases;
    _VKLocalIconAtlas *_localAtlas;
}

+ (id)sharedManager;
- (id)artworkForFeatureID:(unsigned long long)arg1 withResourceNames:(id)arg2 style:(CDStruct_cf20f7af *)arg3 contentScale:(double)arg4;
- (id)_atlasForName:(id)arg1;
- (id)artworkForName:(id)arg1 withResourceNames:(id)arg2 style:(CDStruct_cf20f7af *)arg3 contentScale:(double)arg4 styleAttributes:(id)arg5;
- (id)_defaultAtlasForScale:(double)arg1;
- (void)_didReceiveMemoryWarning:(id)arg1;
- (void)resourceManifestManagerDidChangeActiveTileGroup:(id)arg1;
- (void)resourceManifestManagerWillChangeActiveTileGroup:(id)arg1;
- (void)purge;
- (void)dealloc;
- (id)init;

@end

