//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SGObject.h"

@class NSArray, NSDate, NSObject<OS_dispatch_queue>, NSString, NSTimeZone;

@interface SGEvent : NSObject <SGObject>
{
    NSObject<OS_dispatch_queue> *_geocodeQueue;
    SGEvent *_geocoded;
    BOOL _isAllDay;
    NSString *_title;
    NSString *_messageId;
    NSString *_notes;
    NSDate *_start;
    NSTimeZone *_startTimeZone;
    NSDate *_end;
    NSTimeZone *_endTimeZone;
    NSDate *_creationDate;
    NSDate *_lastModifiedDate;
    NSArray *_locations;
    NSString *_opaqueKey;
    NSArray *_tags;
}

+ (id)eventWithOpaqueKey:(id)arg1 title:(id)arg2 notes:(id)arg3 start:(id)arg4 startTimeZone:(id)arg5 end:(id)arg6 endTimeZone:(id)arg7 isAllDay:(BOOL)arg8 creationDate:(id)arg9 lastModifiedDate:(id)arg10 locations:(id)arg11 tags:(id)arg12 messageId:(id)arg13;
+ (BOOL)supportsSecureCoding;
@property(readonly, nonatomic) NSArray *tags; // @synthesize tags=_tags;
@property(readonly, nonatomic) NSString *opaqueKey; // @synthesize opaqueKey=_opaqueKey;
@property(readonly, nonatomic) NSArray *locations; // @synthesize locations=_locations;
@property(readonly, nonatomic) NSDate *lastModifiedDate; // @synthesize lastModifiedDate=_lastModifiedDate;
@property(readonly, nonatomic) NSDate *creationDate; // @synthesize creationDate=_creationDate;
@property(readonly, nonatomic) BOOL isAllDay; // @synthesize isAllDay=_isAllDay;
@property(readonly, nonatomic) NSTimeZone *endTimeZone; // @synthesize endTimeZone=_endTimeZone;
@property(readonly, nonatomic) NSDate *end; // @synthesize end=_end;
@property(readonly, nonatomic) NSTimeZone *startTimeZone; // @synthesize startTimeZone=_startTimeZone;
@property(readonly, nonatomic) NSDate *start; // @synthesize start=_start;
@property(readonly, nonatomic) NSString *notes; // @synthesize notes=_notes;
@property(readonly, nonatomic) NSString *messageId; // @synthesize messageId=_messageId;
@property(readonly, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (id)description;
- (id)firstLocationForType:(unsigned int)arg1;
- (void)mergeIntoEKEvent:(id)arg1;
- (id)toEKEventWithStore:(id)arg1;
- (unsigned int)hash;
- (BOOL)isEqualToEvent:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)geocodeLocation:(id)arg1 withCallback:(CDUnknownBlockType)arg2;
- (void)geocodeWithCallback:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic, getter=isGeocodeCandidate) BOOL geocodeCandidate;
- (BOOL)isGeocodeCandidateLocation:(id)arg1;
- (id)dateForUTCDate:(id)arg1 withTimeZone:(id)arg2;
- (id)initWithOpaqueKey:(id)arg1 messageId:(id)arg2 title:(id)arg3 notes:(id)arg4 start:(id)arg5 startTimeZone:(id)arg6 end:(id)arg7 endTimeZone:(id)arg8 isAllDay:(BOOL)arg9 creationDate:(id)arg10 lastModifiedDate:(id)arg11 locations:(id)arg12 tags:(id)arg13;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

