/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <WebKit/WebHistoryItem.h>

@interface WebHistoryItem (WebPrivate)
- (id)initWithURL:(id)arg1 title:(id)arg2;
- (id)dictionaryRepresentation;
- (id)dictionaryRepresentationIncludingChildren:(BOOL)arg1;
- (id)target;
- (BOOL)isTargetItem;
- (int)visitCount;
- (id)RSSFeedReferrer;
- (void)setRSSFeedReferrer:(id)arg1;
- (id)children;
- (void)setAlwaysAttemptToUsePageCache:(BOOL)arg1;
- (id)URL;
- (void)_setLastVisitedTimeInterval:(double)arg1;
- (id)_lastVisitedDate;
- (id)targetItem;
- (id)_transientPropertyForKey:(id)arg1;
- (void)_setTransientProperty:(id)arg1 forKey:(id)arg2;
- (BOOL)lastVisitWasFailure;
- (void)_setLastVisitWasFailure:(BOOL)arg1;
- (BOOL)_lastVisitWasHTTPNonGet;
- (id)_redirectURLs;
- (unsigned long)_getDailyVisitCounts:(const int **)arg1;
- (unsigned long)_getWeeklyVisitCounts:(const int **)arg1;
- (void)_setScale:(float)arg1 isInitial:(BOOL)arg2;
- (float)_scale;
- (BOOL)_scaleIsInitial;
- (id)_viewportArguments;
- (void)_setViewportArguments:(id)arg1;
- (struct CGPoint)_scrollPoint;
- (void)_setScrollPoint:(struct CGPoint)arg1;
@end

