/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray, NSMutableArray, ObjectUpdates;

@interface ClockManager : NSObject
{
    _Bool _performingUpgrade;
    NSMutableArray *_scheduledLocalNotifications;
    ObjectUpdates *_localNotificationUpdates;
    _Bool runningInSpringBoard;
    _Bool runningInAssistantPlugin;
    _Bool ignoringNotificationPostRequests;
}

+ (id)sharedManager;
+ (int)sectionFromClockAppURL:(id)arg1;
+ (id)urlForClockAppSection:(int)arg1;
+ (void)saveAndNotifyForUserPreferences:(_Bool)arg1 localNotifications:(_Bool)arg2;
+ (void)loadUserPreferences;
@property(nonatomic, getter=isIgnoringNotificationPostRequests) _Bool ignoringNotificationPostRequests; // @synthesize ignoringNotificationPostRequests;
@property(nonatomic, getter=isRunningInAssistantPlugin) _Bool runningInAssistantPlugin; // @synthesize runningInAssistantPlugin;
@property(nonatomic, getter=isRunningInSpringBoard) _Bool runningInSpringBoard; // @synthesize runningInSpringBoard;
@property(readonly, nonatomic) ObjectUpdates *updatesToLocalNotificationsCache;
@property(readonly, nonatomic) NSArray *scheduledLocalNotificationsCache;
- (void)resetUpdatesToLocalNotificationsCache;
- (void)refreshScheduledLocalNotificationsCache;
- (void)cancelLocalNotification:(id)arg1;
- (void)scheduleLocalNotification:(id)arg1;
- (void)postUserPreferencesChangedNotification;
- (_Bool)discardOldVersion;
- (_Bool)upgrade;
- (_Bool)upgradeIfNeverAttempted;
- (void)dealloc;

@end

