//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface PLCloudTaskManager : NSObject
{
    NSMutableDictionary *_pendingTaskForTaskIdentifier;
    NSMutableDictionary *_resourceForTaskIdentifier;
    NSMutableDictionary *_highPriorityResourceToTaskIdentifierMap;
    NSMutableDictionary *_lowPriorityResourceToTaskIdentifierMap;
}

- (id)_identifierForResource:(id)arg1;
- (void)reportCompletionForResource:(id)arg1 withError:(id)arg2 highPriority:(BOOL)arg3;
- (void)reportProgress:(float)arg1 forResource:(id)arg2 highPriority:(BOOL)arg3;
- (id)addProgressBlock:(CDUnknownBlockType)arg1 completionHandler:(CDUnknownBlockType)arg2 forResource:(id)arg3 highPriority:(BOOL)arg4;
- (void)cancelTaskWithTaskIdentifier:(id)arg1;
- (id)getPendingTaskForTaskIdentifier:(id)arg1;
- (void)createPendingTaskWithProgressBlock:(CDUnknownBlockType)arg1 completionHandler:(CDUnknownBlockType)arg2 forResource:(id)arg3 highPriority:(BOOL)arg4 withTaskIdentifier:(id)arg5;
- (void)setPendingTaskWithTransferTask:(id)arg1 withTaskIdentifier:(id)arg2;
- (void)reset;
- (void)removeTaskIdentifiersForResource:(id)arg1 highPriority:(BOOL)arg2;
- (void)setTaskIdentifiers:(id)arg1 forResource:(id)arg2 highPriority:(BOOL)arg3;
- (id)taskIdentifiersForResource:(id)arg1 highPriority:(BOOL)arg2;
- (id)taskForResource:(id)arg1 highPriority:(BOOL)arg2;
- (id)firstTaskIdentifierForResource:(id)arg1 highPriority:(BOOL)arg2;
- (BOOL)hasTaskIdentifierForResource:(id)arg1 highPriority:(BOOL)arg2;
- (void)dealloc;
- (id)init;

@end

