/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "XPCProxy.h"

@class NSString;

@interface SUManagerClientProxy : XPCProxy
{
    unsigned int _lastAppState;
    int _type;
    int _pid;
    NSString *_identifier;
    BOOL _isApplication;
    BOOL _isMessagable;
    BOOL _isForeground;
}

@property(readonly, nonatomic) BOOL isForeground; // @synthesize isForeground=_isForeground;
@property(readonly, nonatomic) BOOL isMessagable; // @synthesize isMessagable=_isMessagable;
@property(readonly, nonatomic) BOOL isApplication; // @synthesize isApplication=_isApplication;
@property(readonly, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
@property(readonly, nonatomic) int pid; // @synthesize pid=_pid;
@property(nonatomic) int type; // @synthesize type=_type;
- (id)description;
- (void)_applicationStateChanged:(id)arg1;
- (void)_evaluateForegroundness;
- (void)_evaluateMessagability;
- (BOOL)_isStateMessagable:(unsigned int)arg1;
- (BOOL)_isStateForeground:(unsigned int)arg1;
- (void)wakeupIfNecessary;
- (void)dealloc;
- (id)initWithConnection:(struct _xpc_connection_s *)arg1 queue:(struct dispatch_queue_s *)arg2 target:(id)arg3;

@end

