/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iWorkImport/GQDWPLayoutStorage.h>

@interface GQDWPHeaderFooterStorage : GQDWPLayoutStorage
{
    struct __CFString *mName;
}

- (id)initWithName:(struct __CFString *)arg1;
- (void)dealloc;
- (struct __CFString *)name;

@end

