/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface GQHXML : NSObject
{
    id <GQHXMLOutput> mOutput;
    BOOL mUseExternalCss;
    struct __CFString *mFilename;
    struct __CFString *mCssFilename;
    struct __CFString *mCss;
    struct __CFString *mLastCss;
    _Bool isProgressive;
}

@property(readonly) _Bool isProgressive; // @synthesize isProgressive;
- (struct __CFData *)createProgressiveeCSSwithStyleTags:(unsigned char)arg1;
- (struct __CFData *)createProgressiveHtml;
- (BOOL)writeToOutputBundle:(id)arg1;
- (void)addViewportMetaTagForDocumentSize:(struct CGSize)arg1 maximumScale:(float)arg2;
- (void)addViewportMetaTagForDocumentSize:(struct CGSize)arg1;
- (struct __CFString *)cssFilename;
- (void)addStyleClassLast:(struct __CFString *)arg1;
- (void)addStyleClass:(struct __CFString *)arg1;
- (void)addCharRef:(const char *)arg1;
- (void)addXmlCharContent:(const char *)arg1;
- (void)addContent:(struct __CFString *)arg1;
- (void)setAttribute:(const char *)arg1 floatValue:(float)arg2;
- (void)setAttribute:(const char *)arg1 intValue:(int)arg2;
- (void)setAttribute:(const char *)arg1 cfStringValue:(struct __CFString *)arg2;
- (void)setAttribute:(const char *)arg1 value:(const char *)arg2;
- (void)endElementWithExpectedName:(const char *)arg1;
- (void)endElement;
- (void)startElement:(const char *)arg1;
- (void)dealloc;
- (id)initWithFilename:(struct __CFString *)arg1 documentSize:(struct CGSize *)arg2 outputBundle:(id)arg3 useExternalCss:(BOOL)arg4;
- (id)initEmptyWithFilename:(struct __CFString *)arg1 useExternalCss:(BOOL)arg2;

@end

