//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <iWorkImport/KNChart3DBuild.h>

__attribute__((visibility("hidden")))
@interface KNChart3DZAxisBuild : KNChart3DBuild
{
}

+ (id)thumbnailImageNameForType:(int)arg1;
+ (unsigned long long)chartAnimationVersionAdded;
+ (int)chartAnimationType;
+ (id)localizedMenuString:(int)arg1;
+ (id)chartAnimationName;

@end

