//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <iWorkImport/TSPObject.h>

#import "TSDContainerInfo.h"
#import "TSKDocumentObject.h"
#import "TSWPStorageParent.h"

@class NSObject<TSDContainerInfo>, NSString, TSDInfoGeometry, TSPObject<TSDOwningAttachment>, TSWPStorage;

__attribute__((visibility("hidden")))
@interface KNNoteInfo : TSPObject <TSDContainerInfo, TSWPStorageParent, TSKDocumentObject>
{
    NSObject<TSDContainerInfo> *mParentInfo;
    TSWPStorage *mContainedStorage;
    struct CGRect mFrameForPrinting;
    BOOL mShrinkTextForPrinting;
}

@property(nonatomic) NSObject<TSDContainerInfo> *parentInfo; // @synthesize parentInfo=mParentInfo;
@property(retain, nonatomic) TSWPStorage *containedStorage; // @synthesize containedStorage=mContainedStorage;
@property(nonatomic) BOOL shrinkTextForPrinting; // @synthesize shrinkTextForPrinting=mShrinkTextForPrinting;
@property(nonatomic) struct CGRect frameForPrinting; // @synthesize frameForPrinting=mFrameForPrinting;
@property(readonly, nonatomic) int verticalAlignment;
@property(readonly, nonatomic) int contentWritingDirection;
@property(readonly, nonatomic) TSPObject<TSDOwningAttachment> *owningAttachmentNoRecurse;
- (BOOL)shouldHideEmptyBullets;
- (BOOL)textIsVertical;
- (BOOL)autoListTermination;
- (BOOL)autoListRecognition;
- (void)wasRemovedFromDocumentRoot:(id)arg1;
- (void)willBeRemovedFromDocumentRoot:(id)arg1;
- (void)wasAddedToDocumentRoot:(id)arg1 context:(id)arg2;
- (void)willBeAddedToDocumentRoot:(id)arg1 context:(id)arg2;
- (id)childEnumerator;
- (id)childInfos;
- (BOOL)isThemeContent;
- (Class)repClass;
- (Class)layoutClass;
@property(nonatomic) TSPObject<TSDOwningAttachment> *owningAttachment;
@property(readonly, nonatomic, getter=isAttachedToBodyText) BOOL attachedToBodyText;
@property(readonly, nonatomic, getter=isInlineWithText) BOOL inlineWithText;
@property(readonly, nonatomic, getter=isAnchoredToText) BOOL anchoredToText;
@property(readonly, nonatomic, getter=isFloatingAboveText) BOOL floatingAboveText;
- (void)clearBackPointerToParentInfoIfNeeded:(id)arg1;
@property(copy, nonatomic) TSDInfoGeometry *geometry;
- (void)adoptStylesheet:(id)arg1 withMapper:(id)arg2;
- (id)copyWithContext:(id)arg1;
- (void)dealloc;
- (id)initWithContext:(id)arg1;
- (id)initWithContext:(id)arg1 containedStorage:(id)arg2;
- (void)saveToArchive:(struct NoteArchive *)arg1 archiver:(id)arg2;
- (void)loadFromArchive:(const struct NoteArchive *)arg1 unarchiver:(id)arg2;
- (void)saveToArchiver:(id)arg1;
- (id)initFromUnarchiver:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(nonatomic) BOOL matchesObjectPlaceholderGeometry;
@property(readonly) Class superclass;

@end

