//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <iWorkImport/TSABaseApplicationDelegate.h>

@class NSArray;

__attribute__((visibility("hidden")))
@interface TNAppDelegateBase : TSABaseApplicationDelegate
{
}

- (id)templateTypeDisplayName;
- (id)documentTypeDisplayName;
- (id)defaultAppStoreURLString;
- (id)applicationName;
- (id)nativeSFFDocumentType;
- (id)tangierEditingFormatDocumentType;
- (id)templateSFFDocumentType;
- (id)templateDocumentType;
- (id)nativeDocumentType;
- (id)image32IconForTXTFiles;
- (id)previewImageNameForEncryptedNativeDocument;
- (id)previewImageNameForNativeDocument;
- (id)previewImageNameForDocumentType:(id)arg1;
- (id)applicationTemplateVariants;
- (id)appChartPropertyOverrides;
@property(readonly, nonatomic) NSArray *excelDocumentTypes;
- (id)importableDocumentTypes;
- (Class)documentViewControllerClass;
- (id)createCompatibilityDelegate;
- (Class)documentRootClass;
- (void)configureSharedCode;
- (void)wakeUpDownloadManager;
- (void)registerClassTypeMappings;
- (id)init;

@end

