//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <iWorkImport/TSKCommand.h>

@class NSArray, NSIndexSet, TSPObject<TSDMutableContainerInfo>;

__attribute__((visibility("hidden")))
@interface TSDContainerRemoveChildrenCommand : TSKCommand
{
    TSPObject<TSDMutableContainerInfo> *mContainer;
    NSArray *mChildren;
    NSIndexSet *mChildrenIndices;
}

@property(readonly, nonatomic) TSPObject<TSDMutableContainerInfo> *container; // @synthesize container=mContainer;
@property(readonly, nonatomic) NSArray *children; // @synthesize children=mChildren;
- (void)saveToArchiver:(id)arg1;
- (id)initFromUnarchiver:(id)arg1;
- (id)actionString;
- (void)redo;
- (void)undo;
- (void)commit;
- (void)p_do;
- (BOOL)canCoalesceWithCommand:(id)arg1;
- (BOOL)process;
- (void)dealloc;
- (id)initWithContainer:(id)arg1 removingChildren:(id)arg2 objectContext:(id)arg3;

@end

