//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface TSPReaderReferenceInfo : NSObject
{
    long long _objectIdentifier;
    long long _componentIdentifier;
}

+ (id)newReferenceInfoWithObjectIdentifier:(long long)arg1 componentIdentifier:(long long)arg2;
@property(readonly, nonatomic) long long componentIdentifier; // @synthesize componentIdentifier=_componentIdentifier;
@property(readonly, nonatomic) long long objectIdentifier; // @synthesize objectIdentifier=_objectIdentifier;
- (id)initWithObjectIdentifier:(long long)arg1 componentIdentifier:(long long)arg2;
- (id)init;

@end

