//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

__attribute__((visibility("hidden")))
@interface TSTEphemeralFilter : NSObject
{
    unsigned int mFilterIndex;
    unsigned char mColumnIndex;
    NSArray *mRules;
    BOOL mEnabled;
}

+ (id)filterWithIndex:(unsigned int)arg1 columnIndex:(unsigned char)arg2 rules:(id)arg3 enabled:(BOOL)arg4;
@property(readonly, nonatomic) BOOL enabled; // @synthesize enabled=mEnabled;
@property(readonly, nonatomic) unsigned char columnIndex; // @synthesize columnIndex=mColumnIndex;
@property(readonly, nonatomic) unsigned int filterIndex; // @synthesize filterIndex=mFilterIndex;
- (id)description;
- (id)filterByRemovingRuleAtIndex:(unsigned int)arg1;
- (id)filterByAddingRule:(id)arg1;
- (id)filterWithRule:(id)arg1 atIndex:(unsigned int)arg2;
- (id)ruleAtIndex:(unsigned int)arg1;
@property(readonly, nonatomic) unsigned int ruleCount;
- (void)dealloc;
- (id)initWithIndex:(unsigned int)arg1 columnIndex:(unsigned char)arg2 rules:(id)arg3 enabled:(BOOL)arg4;

@end

