/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface WBSpecialCharacter : NSObject
{
}

+ (void)writeCharacterProperties:(id)arg1 to:(id)arg2;
+ (void)writeText:(id)arg1 to:(id)arg2;
+ (void)readFrom:(id)arg1 at:(long)arg2 textRun:(struct WrdCharacterTextRun *)arg3 paragraph:(id)arg4 specialCharacter:(id)arg5;

@end

