/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class AVAsset, MPItemDownloadProperties, NSError, SSDownloadHandlerSession;

@interface MPItemDownloadSession : NSObject
{
    AVAsset *_AVAsset;
    float _percentComplete;
    int _sessionState;
    MPItemDownloadProperties *_downloadProperties;
    SSDownloadHandlerSession *_downloadSession;
    NSError *_sessionError;
}

@property(nonatomic) int sessionState; // @synthesize sessionState=_sessionState;
@property(retain, nonatomic) NSError *sessionError; // @synthesize sessionError=_sessionError;
@property(nonatomic) float percentComplete; // @synthesize percentComplete=_percentComplete;
@property(retain, nonatomic) SSDownloadHandlerSession *downloadSession; // @synthesize downloadSession=_downloadSession;
@property(nonatomic) AVAsset *AVAsset; // @synthesize AVAsset=_AVAsset;
@property(retain, nonatomic) MPItemDownloadProperties *downloadProperties; // @synthesize downloadProperties=_downloadProperties;
- (void).cxx_destruct;
- (id)description;
- (void)snapshotProgressForItem:(id)arg1;
- (void)reloadNetworkConstraints;
- (_Bool)isNetworkConstrainedForNetworkType:(long long)arg1;
- (id)initWithItemDownloadProperties:(id)arg1;

@end

