/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCoding-Protocol.h"

@class ML3AggregateQuery, ML3MusicLibrary, ML3Predicate, NSArray, NSString;

@interface ML3Query : NSObject <NSCoding>
{
    ML3MusicLibrary *_library;
    Class _entityClass;
    ML3Predicate *_predicate;
    NSArray *_orderingProperties;
    NSArray *_directionality;
    BOOL _usingSections;
    ML3AggregateQuery *_nonDirectAggregateQuery;
}

@property(readonly) ML3AggregateQuery *nonDirectAggregateQuery; // @synthesize nonDirectAggregateQuery=_nonDirectAggregateQuery;
@property(readonly) BOOL usingSections; // @synthesize usingSections=_usingSections;
@property(readonly) ML3MusicLibrary *library; // @synthesize library=_library;
@property(readonly) NSArray *orderingProperties; // @synthesize orderingProperties=_orderingProperties;
@property(readonly) ML3Predicate *predicate; // @synthesize predicate=_predicate;
@property(readonly) Class entityClass; // @synthesize entityClass=_entityClass;
@property(readonly) NSString *sectionProperty;
- (void)bindToCountSqlite3Statement:(struct sqlite3_stmt *)arg1 bindingIndex:(inout int *)arg2;
- (id)selectCountSQL;
- (void)bindToPersistentIDsSqlite3Statement:(struct sqlite3_stmt *)arg1 bindingIndex:(inout int *)arg2;
- (id)selectPersistentIDsSQLAndProperties:(id)arg1 ordered:(BOOL)arg2;
- (id)selectPersistentIDsSQL;
- (id)selectUnorderedPersistentIDsSQL;
- (void)bindToSectionsSqlite3Statement:(struct sqlite3_stmt *)arg1 bindingIndex:(inout int *)arg2;
- (id)selectSectionsSQLWithDistinctPersistentIDProperty:(BOOL)arg1;
- (id)selectSQLWithColumns:(id)arg1 groupBy:(id)arg2 orderingProperties:(id)arg3 directionality:(id)arg4;
- (id)selectSQLWithColumns:(id)arg1 groupBy:(id)arg2 orderingProperties:(id)arg3;
- (id)selectSQLWithColumns:(id)arg1 orderingProperties:(id)arg2;
- (id)selectSQLWithColumns:(id)arg1 orderingProperties:(id)arg2 directionality:(id)arg3;
- (id)selectSQLWithColumns:(id)arg1 groupBy:(id)arg2;
- (id)valueForAggregateFunction:(id)arg1 onEntitiesForProperty:(id)arg2;
- (void)enumeratePersistentIDsAndProperties:(id)arg1 countedProperties:(id)arg2 ordered:(BOOL)arg3 cancelBlock:(id)arg4 usingBlock:(void)arg5;
- (void)enumeratePersistentIDsAndProperties:(id)arg1 countedProperties:(id)arg2 ordered:(BOOL)arg3 usingBlock:(id)arg4;
- (void)enumeratePersistentIDsAndProperties:(id)arg1 countedProperties:(id)arg2 usingBlock:(id)arg3;
- (void)enumeratePersistentIDsAndProperties:(id)arg1 usingBlock:(id)arg2;
- (void)enumeratePersistentIDsUsingBlock:(id)arg1;
- (void)enumerateSectionsUsingBlock:(id)arg1;
- (BOOL)distinctPersistentIDProperty;
- (BOOL)deleteAllEntitiesFromLibraryWithDeletionType:(int)arg1;
- (BOOL)deleteAllEntitiesFromLibrary;
- (id)persistentIDProperty;
- (id)sections;
@property(readonly) unsigned int countOfEntities;
@property(readonly) BOOL hasEntities;
- (id)description;
- (void)dealloc;
- (BOOL)isEqual:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithLibrary:(id)arg1 entityClass:(Class)arg2 predicate:(id)arg3 orderingProperties:(id)arg4 usingSections:(BOOL)arg5 nonDirectAggregateQuery:(id)arg6;

@end

