//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKUISwooshViewControllerDelegate.h"

@class SKUIGallerySwooshViewController;

@protocol SKUIGallerySwooshViewControllerDelegate <SKUISwooshViewControllerDelegate>

@optional
- (void)swoosh:(SKUIGallerySwooshViewController *)arg1 didChangePlaybackState:(int)arg2 forItemAtIndex:(int)arg3;
@end

