/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <CoreData/NSManagedObjectContext.h>

@interface NSManagedObjectContext (_NestedContextSupport)
- (void)_copyChildObject:(id)arg1 toParentObject:(id)arg2 fromChildContext:(id)arg3;
- (id)_parentProcessSaveRequest:(id)arg1 inContext:(id)arg2 error:(id *)arg3;
- (id)_parentObjectsForFetchRequest:(id)arg1 inContext:(id)arg2 error:(id *)arg3;
- (id)executeRequest:(id)arg1 withContext:(id)arg2 error:(id *)arg3;
- (void)managedObjectContextDidRegisterObjectsWithIDs:(id)arg1;
- (void)managedObjectContextDidUnregisterObjectsWithIDs:(id)arg1;
- (id)newValuesForObjectWithID:(id)arg1 withContext:(id)arg2 error:(id *)arg3;
- (id)newValueForRelationship:(id)arg1 forObjectWithID:(id)arg2 withContext:(id)arg3 error:(id *)arg4;
- (id)_parentStore;
- (BOOL)_parentObtainPermanentIDsForObjects:(id)arg1 error:(id *)arg2;
@end

