/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <CoreData/NSStoreMapping.h>

@class NSPropertyDescription, NSSQLEntity, NSString;

// Not exported
@interface NSSQLProperty : NSStoreMapping
{
    NSString *_name;
    NSPropertyDescription *_propertyDescription;
    NSSQLEntity *_entity;
    unsigned int _propertyType;
}

- (void)setEntityForReadOnlyFetch:(id)arg1;
- (void)copyValuesForReadOnlyFetch:(id)arg1;
- (unsigned int)slot;
- (id)description;
- (id)entity;
- (id)propertyDescription;
- (_Bool)isEqual:(id)arg1;
- (_Bool)isManyToMany;
- (_Bool)isToMany;
- (_Bool)isToOne;
- (_Bool)isRelationship;
- (_Bool)isOptLockKey;
- (_Bool)isEntityKey;
- (_Bool)isForeignOrderKey;
- (_Bool)isForeignEntityKey;
- (_Bool)isForeignKey;
- (_Bool)isPrimaryKey;
- (_Bool)isAttribute;
- (_Bool)isColumn;
- (unsigned int)propertyType;
- (void)_setName:(id)arg1;
- (id)name;
- (id)externalName;
- (id)columnName;
- (void)setPropertyDescription:(id)arg1;
- (void)dealloc;
- (id)initWithEntity:(id)arg1 propertyDescription:(id)arg2;

@end

