/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iLifeSlideshow/MCObject.h>

@class MCAssetVideo, MCContainerEffect, MCPlugSlide, MCSong, NSArray, NSDictionary, NSMutableDictionary, NSMutableSet, NSString;

@interface MCSlide : MCObject
{
    id *mSlideAsset;
    NSMutableDictionary *mFrameAttributes;
    NSMutableSet *mAnimationPaths;
    NSMutableSet *mFilters;
    NSArray *mCachedOrderedFilters;
    unsigned long long mFlags;
    float mAudioVolume;
    float mAudioDuckLevel;
    MCPlugSlide *mPlug;
    MCSong *mSong;
    unsigned long long mIndex;
    double mAudioFadeInDuration;
    double mAudioFadeOutDuration;
    double mAudioDuckInDuration;
    double mAudioDuckOutDuration;
    double mStartTime;
    double mDuration;
    NSString *mFrameID;
    MCContainerEffect *mContainer;
}

+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
@property MCContainerEffect *container; // @synthesize container=mContainer;
@property(copy) NSString *frameID; // @synthesize frameID=mFrameID;
@property(nonatomic) double duration; // @synthesize duration=mDuration;
@property(nonatomic) double startTime; // @synthesize startTime=mStartTime;
@property(nonatomic) double audioDuckOutDuration; // @synthesize audioDuckOutDuration=mAudioDuckOutDuration;
@property(nonatomic) double audioDuckInDuration; // @synthesize audioDuckInDuration=mAudioDuckInDuration;
@property(nonatomic) float audioDuckLevel; // @synthesize audioDuckLevel=mAudioDuckLevel;
@property(nonatomic) double audioFadeOutDuration; // @synthesize audioFadeOutDuration=mAudioFadeOutDuration;
@property(nonatomic) double audioFadeInDuration; // @synthesize audioFadeInDuration=mAudioFadeInDuration;
@property(nonatomic) float audioVolume; // @synthesize audioVolume=mAudioVolume;
@property(nonatomic) unsigned long long index; // @synthesize index=mIndex;
- (void)_copySelfToSnapshot:(id)arg1;
@property(nonatomic) unsigned char currentLayoutIndex;
@property(readonly) unsigned char countOfLayouts;
@property(copy) NSDictionary *frameAttributes;
- (void)setFrameAttribute:(id)arg1 forKey:(id)arg2;
- (id)frameAttributeForKey:(id)arg1;
@property(readonly) _Bool durationIsDefined;
- (void)undefineDuration;
@property(readonly) _Bool startTimeIsDefined;
- (void)undefineStartTime;
@property(retain) MCPlugSlide *plug; // @synthesize plug=mPlug;
- (void)setSongForAsset:(id)arg1;
@property(readonly) MCSong *song; // @synthesize song=mSong;
@property(nonatomic) double rotation;
@property(nonatomic) double scale;
@property(nonatomic) struct CGPoint center;
@property(copy) NSString *kenBurnsType;
@property(retain) MCAssetVideo *asset;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)imprint;
- (void)demolish;
- (id)initWithImprint:(id)arg1 andMontage:(id)arg2;
- (id)init;

@end

