/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iLifeSlideshow/MPAnimationKeyframe.h>

@interface MPAnimationKeyframe1D : MPAnimationKeyframe
{
    double _scalar;
}

+ (id)keyframe1DWithScalar:(double)arg1 atTime:(double)arg2 offsetType:(unsigned long long)arg3;
+ (id)keyframe1DWithScalar:(double)arg1 atTime:(double)arg2;
@property(nonatomic) double scalar; // @synthesize scalar=_scalar;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initKeyframe1DWithScalar:(double)arg1 atTime:(double)arg2 offsetType:(unsigned long long)arg3;

@end

