/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <Message/MailAccount.h>

@class DAAccount, MFDAMailbox, MFDAOfflineCache, MFRecursiveLock, NSArray, NSCountedSet, NSMutableDictionary, NSObject<ASAccountActorMessages>, NSSet, NSString;

@interface DAMailAccount : MailAccount
{
    NSObject<ASAccountActorMessages> *_accountConduit;
    DAAccount *_daAccount;
    MFRecursiveLock *_offlineCacheLock;
    MFDAOfflineCache *_offlineCache;
    BOOL _isNetworkReachable;
    NSString *_cachedAccountID;
    NSString *_cachedAccountPersistentUUID;
    NSString *_cachedDisplayName;
    NSString *_cachedEmailAddress;
    NSArray *_cachedEmailAddresses;
    NSString *_cachedIconString;
    BOOL _cachedIsHotmailAccount;
    BOOL _cachedCalendarEnabled;
    BOOL _cachedSecureMIMEEnabled;
    BOOL _cachedSecureMIMEShouldSign;
    BOOL _cachedSecureMIMEShouldEncrypt;
    BOOL _cachedRestrictMessageTransfersToOtherAccounts;
    BOOL _cachedRestrictSendingFromExternalProcesses;
    NSString *_cachedInboxFolderID;
    NSString *_cachedSentMessagesFolderID;
    NSString *_cachedTrashFolderID;
    MFDAMailbox *_temporaryInbox;
    BOOL _startListeningOnHierarchyChange;
    BOOL _loadedInitialMailboxList;
    BOOL _receivedInitialMailboxUpdate;
    BOOL _doneInitialInboxCheck;
    BOOL _observingPushedFoldersPrefsChanged;
    int _supportsServerSearch;
    unsigned int _daysToSync;
    NSMutableDictionary *_requestQueuesByFolderID;
    NSSet *_watchedFolderIds;
    NSCountedSet *_userFocusMailboxIds;
}

+ (Class)_accountConduitClass;
+ (id)folderIDForRelativePath:(id)arg1 accountID:(id *)arg2;
+ (id)accountTypeString;
+ (id)displayedAccountTypeString;
+ (id)displayedShortAccountTypeString;
+ (id)_URLScheme;
+ (void)removeStaleExchangeDBRows;
+ (void)_removeStaleExchangeDirectories:(id)arg1;
+ (id)accountIDForDirectoryName:(id)arg1 isAccountDirectory:(char *)arg2;
+ (id)basicAccountProperties;
+ (id)supportedDataclasses;
- (id)initWithLibrary:(id)arg1 properties:(id)arg2;
- (id)initWithDAAccount:(id)arg1;
- (void)foldersContentsChanged:(id)arg1;
- (id)displayName;
- (id)username;
- (id)hostname;
- (id)deliveryAccount;
- (id)uniqueId;
- (id)identifier;
- (id)uniqueIdForPersistentConnection;
- (id)allMailboxUids;
- (void)resetSpecialMailboxes;
- (int)emptyFrequencyForMailboxType:(int)arg1;
- (BOOL)isRunningInDisallowedBundle;
- (void)_loadChildren:(id)arg1 forID:(id)arg2 intoBox:(id)arg3 replacingInbox:(id)arg4 withID:(id)arg5;
- (void)accountHierarchyChanged:(id)arg1;
- (id)accountConduit;
- (void)pushedFoldersPrefsChanged:(id)arg1;
- (BOOL)finishedInitialMailboxListLoad;
- (void)fetchMailboxList;
- (BOOL)_canReceiveNewMailNotifications;
- (Class)storeClass;
- (id)_copyMailboxWithParent:(id)arg1 name:(id)arg2 attributes:(unsigned int)arg3 dictionary:(id)arg4;
- (id)_copyMailboxUidWithParent:(id)arg1 name:(id)arg2 attributes:(unsigned int)arg3 existingMailboxUid:(id)arg4 dictionary:(id)arg5;
- (id)folderIDForMailbox:(id)arg1;
- (void)_synchronouslyLoadListingForParent:(id)arg1;
- (id)_newMailboxWithParent:(id)arg1 name:(id)arg2 attributes:(unsigned int)arg3 dictionary:(id)arg4 withCreationOption:(int)arg5;
- (BOOL)renameMailbox:(id)arg1 newName:(id)arg2 parent:(id)arg3;
- (BOOL)_deleteMailbox:(id)arg1;
- (void)_performFolderChange:(id)arg1 completion:(id)arg2;
- (BOOL)newMailboxNameIsAcceptable:(id)arg1 reasonForFailure:(id *)arg2;
- (BOOL)shouldAppearInMailSettings;
- (id)_URLScheme;
- (id)mailboxPathExtension;
- (void)setDAAccount:(id)arg1;
- (id)syncAnchorForMailbox:(id)arg1;
- (BOOL)supportsRemoteAppend;
- (BOOL)supportsMailboxEditing;
- (id)_infoForMatchingURL:(id)arg1;
- (id)mailboxForFolderID:(id)arg1;
- (id)mailboxUidForInfo:(id)arg1;
- (void)addRequest:(id)arg1 mailbox:(id)arg2 consumer:(id)arg3;
- (void)addRequests:(id)arg1 mailbox:(id)arg2 consumers:(id)arg3;
- (void)processRequests:(id)arg1 mailbox:(id)arg2 consumers:(id)arg3;
- (BOOL)performRequests:(id)arg1 mailbox:(id)arg2 consumers:(id)arg3;
- (BOOL)moveMessages:(id)arg1 fromMailbox:(id)arg2 toMailbox:(id)arg3 markAsRead:(BOOL)arg4 unsuccessfulOnes:(id)arg5;
- (id)_specialMailboxUidWithType:(int)arg1 create:(BOOL)arg2;
- (void)_ensureWeHaveLoadedInitialMailboxList;
- (id)primaryMailboxUid;
- (BOOL)supportsMessageFlagging;
- (BOOL)_isUnitTesting;
- (id)accountPropertyForKey:(id)arg1;
- (void)invalidate;
- (id)iconString;
- (BOOL)derivesDeliveryAccountInfoFromMailAccount;
- (void)dealloc;
- (BOOL)reconstituteOrphanedMeetingInMessage:(id)arg1;
- (id)meetingStorePersistentID;
- (id)_inboxFolderID;
- (void)_updateWatchedFolderIdsAndNotify:(BOOL)arg1;
- (void)startListeningForNotifications;
- (void)stopListeningForNotifications;
- (BOOL)canFetchMessagesByNumericRange;
- (id)syncAnchorForFolderID:(id)arg1 mailbox:(id *)arg2;
- (void)setSyncAnchor:(id)arg1 forFolderID:(id)arg2 mailbox:(id *)arg3;
- (void)performSearchQuery:(id)arg1;
- (void)cancelSearchQuery:(id)arg1;
- (BOOL)shouldDisplayHostnameInErrorMessages;
- (BOOL)shouldRestoreMessagesAfterFailedDelete;
- (BOOL)supportsServerSearch;
- (unsigned int)daysToSync;
- (id)pushedMailboxUids;
- (void)addUserFocusMailbox:(id)arg1;
- (void)removeUserFocusMailbox:(id)arg1;
- (BOOL)canGoOffline;
- (id)_offlineCache;
- (void)_deferMailboxRequests:(id)arg1 mailbox:(id)arg2 offlineCache:(id)arg3;
- (BOOL)_replayOfflineCache:(id)arg1;
- (void)_reachabilityChanged:(id)arg1;
- (id)signingIdentityPersistentReferenceForAddress:(id)arg1;
- (void)setSigningIdentityPersistentReference:(id)arg1 forAddress:(id)arg2;
- (id)encryptionIdentityPersistentReferenceForAddress:(id)arg1;
- (void)setEncryptionIdentityPersistentReference:(id)arg1 forAddress:(id)arg2;
- (BOOL)secureMIMEEnabled;
- (int)secureCompositionSigningPolicyForAddress:(id)arg1;
- (int)secureCompositionEncryptionPolicyForAddress:(id)arg1;
- (id)copyDataForRemoteEncryptionCertificatesForAddress:(id)arg1 error:(id *)arg2;
- (BOOL)restrictedFromTransferingMessagesToOtherAccounts;
- (BOOL)restrictedFromSendingExternally;
- (BOOL)generatesBulletins;
- (void)setGeneratesBulletins:(BOOL)arg1;

@end

