//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionReusableView.h"

#import "UISearchBarDelegate.h"

@class GKSearchBar, NSArray, NSNumber, NSString;

@interface GKSearchBarView : UICollectionReusableView <UISearchBarDelegate>
{
    GKSearchBar *_searchBar;
    NSNumber *_usePadConstraints;
    id <UISearchBarDelegate> _delegate;
    NSArray *_searchBarConstraints;
    float _leadingMargin;
    float _trailingMargin;
}

+ (float)defaultHeight;
+ (void)initialize;
+ (BOOL)requiresConstraintBasedLayout;
@property(nonatomic) float trailingMargin; // @synthesize trailingMargin=_trailingMargin;
@property(nonatomic) float leadingMargin; // @synthesize leadingMargin=_leadingMargin;
@property(retain, nonatomic) NSArray *searchBarConstraints; // @synthesize searchBarConstraints=_searchBarConstraints;
@property(nonatomic) id <UISearchBarDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) NSNumber *usePadConstraints; // @synthesize usePadConstraints=_usePadConstraints;
@property(retain, nonatomic) GKSearchBar *searchBar; // @synthesize searchBar=_searchBar;
- (void)dealloc;
- (void)prepareForReuse;
- (void)applyLayoutAttributes:(id)arg1;
- (void)establishSearchBarConstraints;
- (void)updateConstraints;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

