//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PSThirdPartySettingsDetail : NSObject
{
}

+ (id)preferencesURLForBundleID:(id)arg1 forSettingType:(int)arg2;

@end

