/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "PBCodable.h"

#import "NSCopying-Protocol.h"

@class NSString;

@interface GEODownloadMetadata : PBCodable <NSCopying>
{
    double _timestamp;
    NSString *_etag;
}

@property(retain, nonatomic) NSString *etag; // @synthesize etag=_etag;
@property(nonatomic) double timestamp; // @synthesize timestamp=_timestamp;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(readonly, nonatomic) _Bool hasEtag;
- (void)dealloc;

@end

