//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface EXConditionalFormattingRule : NSObject
{
}

+ (id)edConditionalFormattingRuleFromXmlConditionalFormattingRuleElement:(struct _xmlNode *)arg1 state:(id)arg2;
+ (int)edTimePeriodFromXmlTimePeriodString:(id)arg1;
+ (int)edOperatorFromXmlOperatorString:(id)arg1;
+ (int)edRuleTypeFromXmlRuleTypeString:(id)arg1;

@end

