//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "APSOutgoingMessageOriginator.h"

@class APSTokenState, NSData, NSObject<OS_xpc_object>, NSOperationQueue, NSSet, NSString;

@interface APSConnectionServer : NSObject <APSOutgoingMessageOriginator>
{
    id <APSConnectionServerDelegate> _delegate;
    NSString *_environmentName;
    NSData *_publicToken;
    unsigned int _connectionMachPort;
    NSString *_connectionPortName;
    NSSet *_enabledTopics;
    NSSet *_ignoredTopics;
    NSSet *_opportunisticTopics;
    unsigned int _messageSize;
    unsigned int _largeMessageSize;
    BOOL _enableCriticalReliability;
    BOOL _usesAppLaunchStats;
    BOOL _enableStatusChangeNotifications;
    int _clientPID;
    NSObject<OS_xpc_object> *_connection;
    NSOperationQueue *_queue;
    APSTokenState *_tokenState;
}

+ (id)serversWithEnvironmentName:(id)arg1 delegate:(id)arg2;
+ (id)serverEnvironmentNames;
@property(readonly, retain, nonatomic) NSString *environmentName; // @synthesize environmentName=_environmentName;
@property(nonatomic) NSObject<OS_xpc_object> *connection; // @synthesize connection=_connection;
@property(nonatomic) BOOL enableStatusChangeNotifications; // @synthesize enableStatusChangeNotifications=_enableStatusChangeNotifications;
@property(nonatomic) BOOL usesAppLaunchStats; // @synthesize usesAppLaunchStats=_usesAppLaunchStats;
@property(nonatomic) BOOL enableCriticalReliability; // @synthesize enableCriticalReliability=_enableCriticalReliability;
@property(nonatomic) unsigned int largeMessageSize; // @synthesize largeMessageSize=_largeMessageSize;
@property(nonatomic) unsigned int messageSize; // @synthesize messageSize=_messageSize;
@property(copy, nonatomic) NSData *publicToken; // @synthesize publicToken=_publicToken;
@property(readonly, retain, nonatomic) NSSet *opportunisticTopics; // @synthesize opportunisticTopics=_opportunisticTopics;
@property(readonly, retain, nonatomic) NSSet *ignoredTopics; // @synthesize ignoredTopics=_ignoredTopics;
@property(readonly, retain, nonatomic) NSSet *enabledTopics; // @synthesize enabledTopics=_enabledTopics;
@property(nonatomic) id <APSConnectionServerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, retain, nonatomic) NSString *tokenName;
- (void)_savePersistentConnectionTopics;
@property(readonly, nonatomic) BOOL isConnected; // @dynamic isConnected;
@property(readonly, nonatomic) BOOL hasIdentity; // @dynamic hasIdentity;
- (void)saveAndUpdateDelegate;
- (void)setEnabledTopics:(id)arg1 ignoredTopics:(id)arg2 opportunisticTopics:(id)arg3;
- (void)handleReceivedPerAppToken:(id)arg1 forTopic:(id)arg2 identifier:(id)arg3;
- (void)handleAckIncomingMessageWithGuid:(id)arg1;
- (void)handleInvalidatePerAppTokenForTopic:(id)arg1 identifier:(id)arg2;
- (void)handleRequestPerAppTokenForTopic:(id)arg1 identifier:(id)arg2;
- (void)_requestMissingPerAppTokenForTopic:(id)arg1 identifier:(id)arg2;
- (void)handleFakeMessage:(id)arg1;
- (void)handleCancelOutgoingMessageWithID:(unsigned int)arg1;
- (void)handleSendOutgoingMessage:(id)arg1;
- (void)handleResult:(id)arg1 forSendingOutgoingMessage:(id)arg2;
- (void)handleResult:(id)arg1 forSendingOutgoingMessageWithID:(unsigned int)arg2;
- (void)handleReceivedMessage:(id)arg1;
- (void)_initiateConnectionIfNecessary;
- (void)handleConnectionStatusChanged:(BOOL)arg1;
- (id)connectionPortName;
- (void)connectionInvalidated;
- (void)_suspendQueue;
- (void)_resumeQueue;
- (void)connectionHandshakeDidComplete;
@property(readonly, copy) NSString *debugDescription;
- (id)processNameWithLabels:(BOOL)arg1;
@property(readonly, retain, nonatomic) NSString *processName;
- (void)close;
- (void)_lookUpMachPort;
- (void)dealloc;
- (id)initWithDelegate:(id)arg1 environmentName:(id)arg2 connectionPortName:(id)arg3 connection:(id)arg4;
- (void)_enqueueXPCMessage:(CDUnknownBlockType)arg1 wakingClient:(BOOL)arg2 highPriority:(BOOL)arg3;

// Remaining properties
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

