/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#pragma mark Named Structures

struct BookmarkAndHistoryCompletionMatch;

struct CGPoint {
    double x;
    double y;
};

struct CGRect {
    struct CGPoint _field1;
    struct CGSize _field2;
};

struct CGSize {
    double _field1;
    double _field2;
};

struct Deque<GeolocationChallengeData, 0> {
    unsigned long long m_start;
    unsigned long long m_end;
    struct VectorBuffer<GeolocationChallengeData, 0> m_buffer;
};

struct FrameMetadata {
    void **_field1;
    struct Vector<OpaqueJSValue *, 0, WTF::CrashOnOverflow> _field2;
    struct OpaqueJSValue *_field3;
    struct OpaqueJSValue *_field4;
    struct OpaqueJSContext *_field5;
    struct RetainPtr<id<WBSFormAutoFillFrame>> _field6;
    id _field7;
};

struct GeolocationChallengeData;

struct HashMap<OpaqueFormAutoFillFrame *, WTF::OwnPtr<FrameMetadata>, WTF::PtrHash<OpaqueFormAutoFillFrame *>, WTF::HashTraits<OpaqueFormAutoFillFrame *>, WTF::HashTraits<WTF::OwnPtr<FrameMetadata>>> {
    struct HashTable<OpaqueFormAutoFillFrame *, WTF::KeyValuePair<OpaqueFormAutoFillFrame *, WTF::OwnPtr<FrameMetadata>>, WTF::KeyValuePairKeyExtractor<WTF::KeyValuePair<OpaqueFormAutoFillFrame *, WTF::OwnPtr<FrameMetadata>>>, WTF::PtrHash<OpaqueFormAutoFillFrame *>, WTF::HashMapValueTraits<WTF::HashTraits<OpaqueFormAutoFillFrame *>, WTF::HashTraits<WTF::OwnPtr<FrameMetadata>>>, WTF::HashTraits<OpaqueFormAutoFillFrame *>> m_impl;
};

struct HashMap<WTF::RetainPtr<UIAlertView>, GeolocationChallengeData, WTF::PtrHash<WTF::RetainPtr<UIAlertView>>, WTF::HashTraits<WTF::RetainPtr<UIAlertView>>, WTF::HashTraits<GeolocationChallengeData>> {
    struct HashTable<WTF::RetainPtr<UIAlertView>, WTF::KeyValuePair<WTF::RetainPtr<UIAlertView>, GeolocationChallengeData>, WTF::KeyValuePairKeyExtractor<WTF::KeyValuePair<WTF::RetainPtr<UIAlertView>, GeolocationChallengeData>>, WTF::PtrHash<WTF::RetainPtr<UIAlertView>>, WTF::HashMapValueTraits<WTF::HashTraits<WTF::RetainPtr<UIAlertView>>, WTF::HashTraits<GeolocationChallengeData>>, WTF::HashTraits<WTF::RetainPtr<UIAlertView>>> m_impl;
};

struct HashTable<OpaqueFormAutoFillFrame *, WTF::KeyValuePair<OpaqueFormAutoFillFrame *, WTF::OwnPtr<FrameMetadata>>, WTF::KeyValuePairKeyExtractor<WTF::KeyValuePair<OpaqueFormAutoFillFrame *, WTF::OwnPtr<FrameMetadata>>>, WTF::PtrHash<OpaqueFormAutoFillFrame *>, WTF::HashMapValueTraits<WTF::HashTraits<OpaqueFormAutoFillFrame *>, WTF::HashTraits<WTF::OwnPtr<FrameMetadata>>>, WTF::HashTraits<OpaqueFormAutoFillFrame *>> {
    struct KeyValuePair<OpaqueFormAutoFillFrame *, WTF::OwnPtr<FrameMetadata>> *m_table;
    int m_tableSize;
    int m_tableSizeMask;
    int m_keyCount;
    int m_deletedCount;
};

struct HashTable<WTF::RetainPtr<UIAlertView>, WTF::KeyValuePair<WTF::RetainPtr<UIAlertView>, GeolocationChallengeData>, WTF::KeyValuePairKeyExtractor<WTF::KeyValuePair<WTF::RetainPtr<UIAlertView>, GeolocationChallengeData>>, WTF::PtrHash<WTF::RetainPtr<UIAlertView>>, WTF::HashMapValueTraits<WTF::HashTraits<WTF::RetainPtr<UIAlertView>>, WTF::HashTraits<GeolocationChallengeData>>, WTF::HashTraits<WTF::RetainPtr<UIAlertView>>> {
    struct KeyValuePair<WTF::RetainPtr<UIAlertView>, GeolocationChallengeData> *m_table;
    int m_tableSize;
    int m_tableSizeMask;
    int m_keyCount;
    int m_deletedCount;
};

struct KeyValuePair<OpaqueFormAutoFillFrame *, WTF::OwnPtr<FrameMetadata>>;

struct KeyValuePair<WTF::RetainPtr<UIAlertView>, GeolocationChallengeData>;

struct OpaqueJSContext;

struct OpaqueJSValue;

struct PassRefPtr<SafariShared::BookmarkAndHistoryCompletionMatch> {
    struct BookmarkAndHistoryCompletionMatch *_field1;
};

struct RetainPtr<id<WBSFormAutoFillFrame>> {
    id _field1;
};

struct Vector<OpaqueJSValue *, 0, WTF::CrashOnOverflow> {
    struct OpaqueJSValue **_field1;
    unsigned int _field2;
    unsigned int _field3;
};

struct VectorBuffer<GeolocationChallengeData, 0> {
    struct GeolocationChallengeData *m_buffer;
    unsigned int m_capacity;
    unsigned int m_size;
};

struct _NSRange {
    unsigned long long _field1;
    unsigned long long _field2;
};

#pragma mark Typedef'd Structures

typedef struct {
    struct {
        unsigned short _field1;
        unsigned short _field2;
    } _field1[32];
    unsigned long long _field2;
} CDStruct_f2b84ca7;

// Template types
typedef struct PassRefPtr<SafariShared::BookmarkAndHistoryCompletionMatch> {
    struct BookmarkAndHistoryCompletionMatch *_field1;
} PassRefPtr_8dece646;

