//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSError, NSURL, RCCaptureAudioFileOutput;

@protocol RCCaptureAudioFileOutputRecordingDelegate <NSObject>
- (void)captureOutput:(RCCaptureAudioFileOutput *)arg1 didOutputSampleBuffer:(struct opaqueCMSampleBuffer *)arg2;
- (void)captureOutput:(RCCaptureAudioFileOutput *)arg1 didFinishRecordingToOutputFileAtURL:(NSURL *)arg2 error:(NSError *)arg3;
- (void)captureOutput:(RCCaptureAudioFileOutput *)arg1 didResumeRecordingToOutputFileAtURL:(NSURL *)arg2;
- (void)captureOutput:(RCCaptureAudioFileOutput *)arg1 didPauseRecordingToOutputFileAtURL:(NSURL *)arg2;
- (void)captureOutput:(RCCaptureAudioFileOutput *)arg1 didStartRecordingToOutputFileAtURL:(NSURL *)arg2;
- (void)captureOutput:(RCCaptureAudioFileOutput *)arg1 captureSessionDidTerminateWithError:(NSError *)arg2;
@end

