//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSNumber;

@interface HDMetadataValueResult : NSObject
{
    NSNumber *_objectID;
    NSNumber *_keyID;
    id _value;
}

@property(retain, nonatomic) id value; // @synthesize value=_value;
@property(retain, nonatomic) NSNumber *keyID; // @synthesize keyID=_keyID;
@property(retain, nonatomic) NSNumber *objectID; // @synthesize objectID=_objectID;
- (void).cxx_destruct;

@end

