/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <CommunicationsSetupUI/CNFRegListController.h>

#import "CNFRegWizardControllerDelegate-Protocol.h"

@interface CKSettingsMessagesController : CNFRegListController <CNFRegWizardControllerDelegate>
{
    _Bool _showingChildViewController;
    int _profileToken;
}

- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)controllerForSpecifier:(id)arg1;
- (id)_madridSettingsController;
- (void)_setupAccountHandlersForDisabling;
- (_Bool)_allAccountsAreDeactivated;
- (void)_setupAccountHandlers;
- (void)_updateUIWithError:(id)arg1;
- (void)firstRunControllerDidFinish:(id)arg1 finished:(_Bool)arg2;
- (void)_showMadridSetupIfNecessary;
- (void)_showMadridSetupIfNecessary:(_Bool)arg1;
- (void)dumpLogs:(id)arg1;
- (void)setRegistrationLoggingEnabled:(id)arg1 forSpecifier:(id)arg2;
- (id)isRegistrationLoggingEnabledForSpecifier:(id)arg1;
- (void)setiMessageLoggingEnabled:(id)arg1 forSpecifier:(id)arg2;
- (id)isiMessageLoggingEnabledForSpecifier:(id)arg1;
- (id)debugSettingsSpecifierIdentifiers;
- (_Bool)shouldShowDebugSettings;
- (id)madridSigninButtonTextForSpecifier:(id)arg1;
- (void)madridSigninTappedWithSpecifier:(id)arg1;
- (id)madridSigninSpecifiers;
- (_Bool)shouldShowMadridSignin;
- (id)getAccountSummaryForSpecifier:(id)arg1;
- (id)madridAccountsSpecifierIdentifiers;
- (_Bool)shouldShowMadridAccounts;
- (id)sendAsSMSIdentifiers;
- (_Bool)shouldShowSendAsSMS;
- (void)setReadReceiptsEnabled:(id)arg1 specifier:(id)arg2;
- (id)areReadReceiptsEnabled:(id)arg1;
- (id)readReceiptSpecifierIdentifiers;
- (_Bool)shouldShowReadReceipts;
- (id)blacklistSettingsSpecifierIdentifiers;
- (_Bool)shouldShowBlacklistSettings;
- (id)characterCountSpecifierIdentifiers;
- (_Bool)shouldShowCharacterCount;
- (id)genericSettingsSpecifierIdentifiers;
- (_Bool)shouldShowGenericSettings;
- (void)_updateSwitchDelayed;
- (void)_updateSwitch;
- (id)_switchFooterText:(_Bool *)arg1;
- (void)setMadridEnabled:(id)arg1 specifier:(id)arg2;
- (id)isMadridEnabled:(id)arg1;
- (id)madridSwitchSpecifierIdentifiers;
- (_Bool)shouldShowMadridSwitch;
- (_Bool)_isMadridSwitchOn;
- (_Bool)_isMadridAccountOperational;
- (_Bool)_isSMSDevice;
- (void)setWillSendGroupMMS:(id)arg1 specifier:(id)arg2;
- (id)willSendGroupMMS:(id)arg1;
- (void)setMMSEnabled:(id)arg1 specifier:(id)arg2;
- (id)isMMSEnabled:(id)arg1;
- (void)setDeliveryReportsEnabled:(id)arg1 specifier:(id)arg2;
- (id)isDeliveryReportsEnabled:(id)arg1;
- (id)deliveryReceiptSpecifierIdentifiers;
- (_Bool)shouldShowDeliveryReceipts;
- (void)setSpecifierLoading:(id)arg1 loading:(_Bool)arg2 animated:(_Bool)arg3;
- (id)specifiers;
- (void)newCarrierNotification;
- (_Bool)shouldReloadSpecifiersOnResume;
- (void)systemApplicationDidEnterBackground;
- (void)systemApplicationWillEnterForeground;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (_Bool)wantsWiFiChooser;
- (void)_stopListeningForProfileChanges;
- (void)_startListeningForProfileChanges;
- (id)logName;
- (void)dealloc;
- (id)bundle;
- (id)init;

@end

