//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CALayer.h"

@class AVPlayer, AVPlayerLayerInternal, NSString;

@interface AVPlayerLayer : CALayer
{
    AVPlayerLayerInternal *_playerLayer;
}

+ (id)keyPathsForValuesAffectingVideoRect;
+ (id)playerLayerWithPlayer:(id)arg1;
- (struct CGRect)_minRectToFitVideoAndSubtitlesInBounds:(struct CGRect)arg1;
- (struct CGRect)_videoRectForBounds:(struct CGRect)arg1;
@property(readonly, nonatomic) struct CGRect videoRect;
- (void)setOverscanSubtitleSupportEnabled:(BOOL)arg1;
- (BOOL)isOverscanSubtitleSupportEnabled;
- (float)_pctOfSubtitleLayerHeight;
- (void)_setSubtitleGravity:(id)arg1;
- (id)_subtitleGravity;
- (void)_setSubtitleDisplayEnabled:(BOOL)arg1;
- (BOOL)_subtitleDisplayEnabled;
- (void)_setItem:(id)arg1 readyForDisplay:(BOOL)arg2;
@property(readonly, nonatomic, getter=isReadyForDisplay) BOOL readyForDisplay;
@property(copy) NSString *videoGravity;
- (void)layerDidBecomeVisible:(BOOL)arg1;
@property(retain, nonatomic) AVPlayer *player;
- (void)_subtitlesDidChange:(id)arg1;
- (void)subtitleLayerNeedsLayout:(id)arg1;
- (void)_updateSubtitles:(id)arg1 forceRender:(BOOL)arg2;
- (void)_updateSubtitleLayerForPlayerLayerBounds:(struct CGRect)arg1 presentationSize:(struct CGSize)arg2 playLayerTransform:(struct CATransform3D)arg3 forceRender:(BOOL)arg4;
- (void)_calculateSubtitleLayerBounds:(struct CGRect)arg1 presentationSize:(struct CGSize)arg2 playLayerTransform:(struct CATransform3D)arg3 shouldUpdateCachedSubtitleSample:(BOOL)arg4 outBound:(struct CGRect *)arg5;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)_setHasPlayerToObserve:(int)arg1 andShouldObserveIt:(int)arg2;
- (void)_updatePresentationSize:(struct CGSize)arg1 forceUpdate:(BOOL)arg2;
- (struct CGSize)_getAVPlayerCurrentItemPresentationSizeKeyFromPlayer:(id)arg1;
- (void)_disconnectContentLayerFromPlayer;
- (void)_connectContentLayerToPlayer;
- (void)finalize;
- (void)dealloc;
- (void)removeAllAnimations;
- (void)removeAnimationForKey:(id)arg1;
- (void)addAnimation:(id)arg1 forKey:(id)arg2;
- (void)_addAnimationsForSubtitleLayer:(id)arg1 size:(struct CGSize)arg2;
- (void)_addAnimationsForContentLayer:(id)arg1 size:(struct CGSize)arg2 gravity:(id)arg3;
- (void)_addAnimationsForMaskLayer:(id)arg1;
- (void)setBounds:(struct CGRect)arg1;
- (id)initWithLayer:(id)arg1;
- (id)init;

@end

