//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark Blocks

typedef void (^CDUnknownBlockType)(void); // return type and parameters are unknown

#pragma mark Named Structures

struct CGPoint {
    float x;
    float y;
};

struct _CCCryptor;

#pragma mark Typedef'd Structures

typedef struct {
    struct _CCCryptor *_field1;
    unsigned char _field2[16];
    unsigned char _field3[16];
    unsigned int _field4;
} CDStruct_86971917;

