//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData;

@interface UDPPacketToSend : NSObject
{
    int _state;
    int _numberOfChecks;
    int _numberOfRetransmits;
    unsigned short _eventNumber;
    NSData *_data;
}

@property(retain) NSData *data; // @synthesize data=_data;
@property unsigned short eventNumber; // @synthesize eventNumber=_eventNumber;
@property int numberOfRetransmits; // @synthesize numberOfRetransmits=_numberOfRetransmits;
@property int numberOfChecks; // @synthesize numberOfChecks=_numberOfChecks;
@property int state; // @synthesize state=_state;
- (void)dealloc;
- (id)initWithBytes:(char *)arg1 length:(unsigned short)arg2 eventNum:(unsigned short)arg3;

@end

