/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <PhotosUI/PUAbstractAlbumListViewController.h>

#import "PUCollectionViewReorderDelegate-Protocol.h"
#import "PUSectionedGridLayoutDelegate-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"

@class PUAlbumListTransitionContext, PUCollectionView, PUSectionedGridLayout, UICollectionViewLayout;

@interface PUAlbumListGridViewController : PUAbstractAlbumListViewController <UICollectionViewDataSource, UICollectionViewDelegate, PUCollectionViewReorderDelegate, PUSectionedGridLayoutDelegate>
{
    PUCollectionView *__mainCollectionView;
    PUSectionedGridLayout *__mainCollectionViewLayout;
    PUAlbumListTransitionContext *_albumListTransitionContext;
    UICollectionViewLayout *__albumListTransitionLayout;
}

@property(retain, nonatomic, setter=setAlbumListTransitionLayout:) UICollectionViewLayout *_albumListTransitionLayout; // @synthesize _albumListTransitionLayout=__albumListTransitionLayout;
@property(retain, nonatomic) PUAlbumListTransitionContext *albumListTransitionContext; // @synthesize albumListTransitionContext=_albumListTransitionContext;
@property(retain, nonatomic, setter=_setMainCollectionViewLayout:) PUSectionedGridLayout *_mainCollectionViewLayout; // @synthesize _mainCollectionViewLayout=__mainCollectionViewLayout;
@property(retain, nonatomic, setter=_setMainCollectionView:) PUCollectionView *_mainCollectionView; // @synthesize _mainCollectionView=__mainCollectionView;
- (void).cxx_destruct;
- (id)newGridViewControllerForStandInAlbum:(struct NSObject *)arg1;
- (id)collectionView:(id)arg1 transitionLayoutForOldLayout:(id)arg2 newLayout:(id)arg3;
- (void)handleTransitionFade:(_Bool)arg1 animate:(_Bool)arg2;
- (void)setAlbumListTransitionLayout:(id)arg1 animated:(_Bool)arg2;
- (id)gridLayout;
- (id)collectionView;
- (id)sectionedGridLayoutAnchorItemForAdjustingContentOffset:(id)arg1;
- (id)sectionedGridLayout:(id)arg1 sectionsForVisualSection:(long long)arg2;
- (long long)numberOfVisualSectionsForSectionedGridLayout:(id)arg1;
- (void)collectionView:(id)arg1 moveItemAtIndexPath:(id)arg2 toIndexPath:(id)arg3 completionHandler:(id)arg4;
- (id)collectionView:(id)arg1 targetIndexPathForMoveFromIndexPath:(id)arg2 toProposedIndexPath:(id)arg3;
- (_Bool)collectionView:(id)arg1 canReorderItemAtIndexPath:(id)arg2;
- (void)setSyncProgressVisible:(_Bool)arg1;
- (void)configureSupplementaryView:(id)arg1 ofKind:(id)arg2 forIndexPath:(id)arg3 animated:(_Bool)arg4;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (_Bool)collectionView:(id)arg1 shouldHighlightItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (long long)cellContentViewLayout;
- (_Bool)showsDeleteButtonOnCellContentView;
- (struct PUAlbumListCellContentView *)visiblePlaceholderListCellContentViewAtIndexPath:(id)arg1;
- (id)visibleAlbumListCellContentViewAtIndexPath:(id)arg1;
- (id)indexPathForAlbumListCellContentView:(id)arg1;
- (id)indexPathForItemAtPoint:(struct CGPoint)arg1;
- (id)indexPathsForVisibleItems;
- (id)mainScrollView;
- (void)performBatchUpdatesWithDeletedIndexPaths:(id)arg1 insertedIndexPaths:(id)arg2 changedIndexPaths:(id)arg3 movedFromIndexPaths:(id)arg4 movedToIndexPaths:(id)arg5 completionHandler:(id)arg6;
- (void)visiblyInsertItemAtIndexPath:(id)arg1 completionHandler:(id)arg2;
- (void)scrollToItemAtIndexPath:(id)arg1 centered:(_Bool)arg2 animated:(_Bool)arg3;
- (void)reloadContentView;
- (void)viewDidLoad;
- (void)dealloc;

@end

