/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface PULayoutSectionSampler : NSObject
{
}

- (void)dumpInternalMemory;
- (void)enumerateUnsampledIndexesForSampledIndexInRange:(struct _NSRange)arg1 usingBlock:(id)arg2;
- (long long)unsampledIndexForIndex:(long long)arg1;
- (long long)indexForUnsampledIndex:(long long)arg1 isMainItem:(_Bool *)arg2;

@end

