/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIView.h"

@class NSIndexSet, NSString, UIColor;

@interface EKDayOccurrenceContentView : UIView
{
    NSString *_title;
    NSString *_location;
    UIColor *_color;
    UIColor *_textColor;
    NSIndexSet *_titleMetrics;
    NSIndexSet *_locationMetrics;
    struct CGPoint _titleEndPoint;
    float _textEndY;
    struct CGRect _titleRect;
    struct CGRect _locationRect;
    struct CGRect _fullTextRect;
    BOOL _isAllDay;
    BOOL _isBirthday;
    BOOL _isFacebook;
    BOOL _usesSmallText;
    BOOL _cancelled;
    BOOL _tentative;
    BOOL _needsReply;
    BOOL _borderless;
    BOOL _dimmed;
    BOOL _dragging;
}

+ (Class)layerClass;
@property(nonatomic) BOOL dragging; // @synthesize dragging=_dragging;
@property(nonatomic, getter=isDimmed) BOOL dimmed; // @synthesize dimmed=_dimmed;
@property(nonatomic, getter=isBorderless) BOOL borderless; // @synthesize borderless=_borderless;
@property(nonatomic) BOOL needsReply; // @synthesize needsReply=_needsReply;
@property(nonatomic, getter=isTentative) BOOL tentative; // @synthesize tentative=_tentative;
@property(nonatomic, getter=isCancelled) BOOL cancelled; // @synthesize cancelled=_cancelled;
@property(nonatomic) BOOL usesSmallText; // @synthesize usesSmallText=_usesSmallText;
@property(retain, nonatomic) UIColor *color; // @synthesize color=_color;
@property(nonatomic, getter=isFacebook) BOOL facebook; // @synthesize facebook=_isFacebook;
@property(nonatomic, getter=isBirthday) BOOL birthday; // @synthesize birthday=_isBirthday;
@property(nonatomic, getter=isAllDay) BOOL allDay; // @synthesize allDay=_isAllDay;
@property(copy, nonatomic) NSString *location; // @synthesize location=_location;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (id)_allDayDashedOutlineWithColor:(id)arg1;
- (id)_dashedOutline;
- (id)_locationMetricsForSize:(struct CGSize)arg1;
- (id)_locationFont;
- (id)_textColor;
- (void)_getTitleMetrics:(id *)arg1 endPoint:(struct CGPoint *)arg2 forSize:(struct CGSize)arg3;
- (void)setFrame:(struct CGRect)arg1;
- (void)setBounds:(struct CGRect)arg1;
- (id)_titleFont;
- (void)_invalidateMetrics;
- (void)dealloc;
- (id)initWithContentView:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)displayLayer:(id)arg1;
- (void)setNeedsDisplay;

@end

