//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, UIImage;

@interface _MPGeniusMixArtworkCache : NSObject
{
    NSData *_data;
    UIImage *_artworkImage;
}

+ (id)artworkCacheWithContentsOfFile:(id)arg1;
+ (id)artworkCacheWithCoverCount:(unsigned int)arg1 coverSize:(struct CGSize)arg2 entityArtworkCacheHash:(unsigned long long)arg3 artworkData:(void *)arg4 length:(unsigned int)arg5;
- (void).cxx_destruct;
- (BOOL)writeToFile:(id)arg1;
@property(readonly, nonatomic) unsigned long long entityArtworkCacheHash;
@property(readonly, nonatomic) struct CGSize coverSize;
@property(readonly, nonatomic) unsigned int coverCount;
@property(readonly, nonatomic) UIImage *artworkImage;
- (id)init;

@end

