/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIPasteboard.h"

@interface UIPasteboard (MFAttachmentsPasteboardSupport)
- (id)mf_getAttachmentsPasteboardRepresentations;
- (void)mf_addPasteboardRepresentationsForAttachments:(id)arg1;
- (void)mf_addPasteboardRepresentationsForTextAttachments:(id)arg1;
@end

