//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <MusicUI/MusicTableViewController.h>

#import "MusicPickerOverlayDelegate.h"
#import "UITextFieldDelegate.h"

@class NSCache, UIAlertView, UITextField;

@interface MusicPlaylistsViewController : MusicTableViewController <MusicPickerOverlayDelegate, UITextFieldDelegate>
{
    UITextField *_newPlaylistAlertTextField;
    id _newPlaylistAlertTextFieldChangeObserver;
    UIAlertView *_newPlaylistAlertView;
    NSCache *_playlistMetadataCache;
}

@property(retain, nonatomic) NSCache *playlistMetadataCache; // @synthesize playlistMetadataCache=_playlistMetadataCache;
- (void).cxx_destruct;
- (void)_updateCloudPlaylist:(id)arg1;
- (id)_playlistTitle;
- (void)createGeniusPlaylistAction;
- (void)addPlaylistAction;
- (BOOL)textFieldShouldReturn:(id)arg1;
- (BOOL)_isSaveButtonEnabled;
- (void)_updateSaveButtonEnabledState;
- (void)tableView:(id)arg1 commitEditingStyle:(int)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(int)arg2;
- (void)pickerOverlayDidFinish:(id)arg1;
- (void)pickerOverlayRequestsFinish:(id)arg1;
- (void)reloadData;
- (BOOL)music_hasContent;
- (BOOL)MPH_supportsCoverFlow;
- (void)switchToShortcutIdentifier:(id)arg1;
- (id)initWithDataSource:(id)arg1 cellConfigurationClass:(Class)arg2;

@end

