/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UITableViewCell.h"

@class MPUSeparatorView, NSString, UILabel;

@interface _RUGenreListTableViewCell : UITableViewCell
{
    MPUSeparatorView *_separatorView;
    UILabel *_titleLabel;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *genreName;
- (void)layoutSubviews;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

