/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSArray.h"

@interface CALayerArray : NSArray
{
    struct _CALayerArrayIvars _ivars;
}

- (id)initWithLayers:(id *)arg1 count:(unsigned long)arg2 retain:(BOOL)arg3;
- (void)dealloc;
- (unsigned int)count;
- (id)objectAtIndex:(unsigned int)arg1;
- (void)getObjects:(id *)arg1;
- (void)getObjects:(id *)arg1 range:(struct _NSRange)arg2;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;
- (unsigned int)countByEnumeratingWithState:(CDStruct_11f37819 *)arg1 objects:(id *)arg2 count:(unsigned int)arg3;

@end

