/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <StoreServices/SSRequest.h>

#import "SSCoding-Protocol.h"

@class NSURLRequest;

@interface SSDownloadManifestRequest : SSRequest <SSCoding>
{
    int _manifestFormat;
    BOOL _shouldHideUserPrompts;
    NSURLRequest *_urlRequest;
}

@property(nonatomic) BOOL shouldHideUserPrompts; // @synthesize shouldHideUserPrompts=_shouldHideUserPrompts;
@property(nonatomic) int manifestFormat; // @synthesize manifestFormat=_manifestFormat;
- (void)_sendResponseToDelegate:(id)arg1;
- (BOOL)issueRequestForIdentifier:(id)arg1 error:(id *)arg2;
- (BOOL)handleFinishResponse:(id)arg1 error:(id *)arg2;
@property(readonly) NSURLRequest *URLRequest;
- (id)initWithXPCEncoding:(void *)arg1;
- (id)initWithPropertyListEncoding:(id)arg1;
- (void *)copyXPCEncoding;
- (id)copyPropertyListEncoding;
- (void)dealloc;
- (id)initWithURLRequest:(id)arg1;
- (id)init;

// Remaining properties
@property(nonatomic) id <SSDownloadManifestRequestDelegate> delegate; // @dynamic delegate;

@end

