//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BRCAccountSession, BRCItemID, BRCLocalContainer, NSMutableIndexSet, NSObject<OS_dispatch_group>;

__attribute__((visibility("hidden")))
@interface BRCTreeEnumerator : NSObject
{
    BRCLocalContainer *_container;
    BRCAccountSession *_session;
    CDUnknownBlockType _handler;
    BRCItemID *_parentID;
    unsigned int _rowID;
    NSMutableIndexSet *_seen;
    NSMutableIndexSet *_toVisit;
    NSObject<OS_dispatch_group> *_group;
    CDUnknownBlockType _whenDone;
}

@property(copy, nonatomic) CDUnknownBlockType whenDone; // @synthesize whenDone=_whenDone;
- (void).cxx_destruct;
- (void)_iterateWithoutParent:(unsigned int)arg1;
- (void)_iterate:(unsigned int)arg1;
- (void)_visitNewParent:(unsigned int)arg1;
- (void)_scheduleAsync;
- (void)enumerateBelow:(id)arg1 group:(id)arg2;
- (void)done;
- (id)initWithContainer:(id)arg1 handler:(CDUnknownBlockType)arg2;

@end

