/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

// Not exported
@interface KNNoteController : NSObject
{
}

+ (id)slideNodeForNoteSearchTarget:(id)arg1;
+ (unsigned long long)rootSearchTargetIndexForSlideNodeIndex:(unsigned long long)arg1 isEditingNote:(_Bool)arg2;
+ (unsigned long long)slideNodeIndexForRootSearchTargetIndex:(unsigned int)arg1;
+ (_Bool)isNoteAtRootSearchTargetIndex:(unsigned int)arg1;
+ (_Bool)isNoteSearchTarget:(id)arg1;
+ (id)noteSearchTargetForSlideNode:(id)arg1;

@end

