/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iWorkImport/TPFootnoteContainerLayout.h>

// Not exported
@interface TPInflatableFootnoteContainerLayout : TPFootnoteContainerLayout
{
    _Bool _inflated;
}

- (id)computeLayoutGeometry;
- (void)validate;
- (void)setNeedsInflation;

@end

