/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray, TSDFPSCounter;

// Not exported
@interface TSCH3DChartRepFPSCounter : NSObject
{
    TSDFPSCounter *mCounter;
    NSMutableArray *mSummaries;
    unsigned long long mCurrentFrameCount;
}

- (void)dumpAllSummaries;
- (void)dumpSummary;
- (void)addFrame;
- (void)resetAll;
- (void)resetCounters;
- (void)dealloc;
- (id)init;

@end

