/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iWorkImport/TSSStyle.h>

@class NSArray, TSCHChartStyle, TSCHLegendStyle, TSCHPropertyValueStorageContainer, TSWPParagraphStyle, TSWPShapeStyle;

// Not exported
@interface TSCHStylePasteboardData : TSSStyle
{
    TSCHPropertyValueStorageContainer *mStyleNetwork;
    _Bool mEntireChart;
    TSWPParagraphStyle *mInteropParagraphStyle;
    TSWPShapeStyle *mInteropShapeStyle;
}

+ (id)properties;
@property(nonatomic) _Bool entireChart; // @synthesize entireChart=mEntireChart;
@property(retain, nonatomic) TSWPShapeStyle *interopShapeStyle; // @synthesize interopShapeStyle=mInteropShapeStyle;
@property(retain, nonatomic) TSWPParagraphStyle *interopParagraphStyle; // @synthesize interopParagraphStyle=mInteropParagraphStyle;
- (void)saveToArchiver:(id)arg1;
- (id)initFromUnarchiver:(id)arg1;
- (id)chartStyleStateWithMapper:(id)arg1;
- (id)stylesheet;
- (id)pasteboardDescription;
- (id)allStyles;
@property(copy, nonatomic) NSArray *paragraphStyles;
@property(copy, nonatomic) NSArray *seriesStyles;
@property(copy, nonatomic) NSArray *categoryAxisStyles;
@property(copy, nonatomic) NSArray *valueAxisStyles;
@property(retain, nonatomic) TSCHLegendStyle *legendStyle;
@property(retain, nonatomic) TSCHChartStyle *chartStyle;
- (void)dealloc;
- (id)initWithContext:(id)arg1;
- (id)initWithContext:(id)arg1 name:(id)arg2 overridePropertyMap:(id)arg3 isVariation:(_Bool)arg4;

@end

