/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCopying-Protocol.h"

@class NSIndexSet;

// Not exported
@interface TSTCellRegion : NSObject <NSCopying>
{
    unsigned long long mCellRangesCount;
    CDStruct_5f1f7aa9 *mCellRanges;
    CDStruct_5f1f7aa9 mBoundingCellRange;
    unsigned long long mCellCount;
    NSIndexSet *mIntersectingColumnsIndexSet;
    NSIndexSet *mIntersectingRowsIndexSet;
    CDStruct_0441cfb5 mUpperLeftCellID;
    CDStruct_0441cfb5 mBottomRightCellID;
}

+ (id)regionFromColumnIndices:(id)arg1;
+ (id)regionFromRowIndices:(id)arg1;
+ (id)regionFillingRowsFromRegion:(id)arg1;
+ (id)regionFillingColumnsFromRegion:(id)arg1;
+ (id)invalidRegion;
+ (id)region:(id)arg1 subtractingRegion:(id)arg2;
+ (id)region:(id)arg1 addingRegion:(id)arg2;
+ (id)unionEveryRangeInRegion:(id)arg1 withRange:(CDStruct_5f1f7aa9)arg2;
+ (id)region:(id)arg1 intersectingRange:(CDStruct_5f1f7aa9)arg2;
+ (id)region:(id)arg1 subtractingRange:(CDStruct_5f1f7aa9)arg2;
+ (id)region:(id)arg1 addingRange:(CDStruct_5f1f7aa9)arg2;
+ (id)regionFromCellMap:(id)arg1;
+ (id)regionFromRange:(CDStruct_5f1f7aa9)arg1;
- (id).cxx_construct;
- (id)description;
- (void)p_calculateUpperLeftAndBottomRightCellID;
- (void)p_calculateIntersectingRows;
- (void)p_calculateIntersectingColumns;
- (void)p_calculateAncillaryInformation;
- (void)p_insertRangeIntoRegion:(CDStruct_5f1f7aa9)arg1;
- (void)enumerateColumnRangesUsingBlock:(id)arg1;
- (void)enumerateRowRangesUsingBlock:(id)arg1;
- (void)enumerateInDirection:(int)arg1 usingBlock:(id)arg2;
- (void)enumerateRowsUsingBlock:(id)arg1;
- (void)enumerateColumnsUsingBlock:(id)arg1;
- (void)enumerateCellRangesUsingBlock:(id)arg1;
- (void)enumerateCellIDsUsingBlock:(id)arg1;
- (struct NSObject *)topToBottomIterator;
- (struct NSObject *)rightToLeftIterator;
- (struct NSObject *)iterator;
- (CDStruct_0441cfb5)suitableCursor;
- (CDStruct_0441cfb5)suitableAnchor;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (_Bool)isValid;
- (id)intersectingRowsIndexSet;
- (id)intersectingColumnsIndexSet;
@property(readonly, nonatomic) unsigned short numberOfIntersectingRows;
@property(readonly, nonatomic) unsigned short numberOfIntersectingColumns;
- (_Bool)intersectsRow:(unsigned short)arg1;
- (_Bool)intersectsColumn:(unsigned char)arg1;
- (_Bool)partiallyIntersectsCellRange:(CDStruct_5f1f7aa9)arg1;
- (_Bool)intersectsCellRange:(CDStruct_5f1f7aa9)arg1;
- (_Bool)equalsCellRange:(CDStruct_5f1f7aa9)arg1;
- (_Bool)equalsCellRegion:(id)arg1;
- (_Bool)containsCellRegion:(id)arg1;
- (_Bool)containsCellRange:(CDStruct_5f1f7aa9)arg1;
- (_Bool)containsCellID:(CDStruct_0441cfb5)arg1;
@property(readonly, nonatomic) _Bool isRectangle;
@property(readonly, nonatomic) _Bool isEmpty;
@property(readonly, nonatomic) unsigned long long cellCount;
@property(readonly, nonatomic) CDStruct_5f1f7aa9 boundingCellRange;
@property(readonly, nonatomic) CDStruct_0441cfb5 bottomRightCellID;
@property(readonly, nonatomic) CDStruct_0441cfb5 upperLeftCellID;
- (id)regionByApplyingRowMapping:(id)arg1;
- (id)regionByAddingColumns:(id)arg1;
- (id)regionByAddingRows:(id)arg1;
- (id)regionByIntersectingColumnIndices:(id)arg1;
- (id)regionByIntersectingRowIndices:(id)arg1;
- (id)regionByRemovingColumns:(id)arg1;
- (id)regionByRemovingRows:(id)arg1;
- (id)regionOffsetBy:(CDStruct_79c71658)arg1;
- (id)regionBySubtractingRegion:(id)arg1;
- (id)regionByAddingRegion:(id)arg1;
- (id)regionByUnioningEveryRangeInRegionWithRange:(CDStruct_5f1f7aa9)arg1;
- (id)regionByIntersectingRange:(CDStruct_5f1f7aa9)arg1;
- (id)regionBySubtractingRange:(CDStruct_5f1f7aa9)arg1;
- (id)regionByAddingRange:(CDStruct_5f1f7aa9)arg1;
- (void)saveToMessage:(struct CellRegion *)arg1;
- (id)initFromMessage:(const struct CellRegion *)arg1;
- (void)dealloc;
- (id)init;

@end

