/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSAttributedString, NSString;

@interface CPReadingModel : NSObject
{
    long long _count;
    CDStruct_627e0f85 *_textLineRanges;
    CDStruct_627e0f85 *_stringLineRanges;
    long long *_pageNumbers;
    CDStruct_627e0f85 _pageRange;
    struct CGPDFDocument *_document;
    long long _numberOfLines;
    long long _numberOfParagraphs;
    long long _numberOfColumns;
    long long _numberOfLayoutAreas;
    NSString *_cachedString;
    NSAttributedString *_cachedAttributedString;
    long long _pageNumber;
    long long _pos;
}

- (long long)lineIndexForPoint:(struct CGPoint)arg1 onPage:(unsigned long long)arg2;
- (struct _NSRange)linesForPage:(unsigned long long)arg1;
- (struct _NSRange)pageRangeForStringRange:(CDStruct_627e0f85)arg1;
- (struct _NSRange)stringRangeForTextRangeBUGGY:(CDStruct_627e0f85)arg1;
- (struct _NSRange)stringRangeForTextRange:(CDStruct_627e0f85)arg1 onPageNumber:(unsigned long long)arg2;
- (id)attributedStringForLine:(unsigned long long)arg1;
- (id)stringForLine:(unsigned long long)arg1;
- (CDStruct_627e0f85)textRangeForStringRange:(struct _NSRange)arg1;
- (struct CGRect)pdfBoundsForRange:(struct _NSRange)arg1;
- (struct _NSRange)rangeForLine:(unsigned long long)arg1;
- (unsigned long long)lineForIndex:(unsigned long long)arg1;
- (id)attributedStringForRange:(struct _NSRange)arg1;
- (id)attributedString;
- (id)stringForRange:(struct _NSRange)arg1;
- (id)string;
- (struct CGRect)pdfBoundsForLine:(unsigned long long)arg1;
- (struct _NSRange)textRangeForLine:(unsigned long long)arg1;
- (struct _NSRange)stringRangeForLine:(unsigned long long)arg1;
- (unsigned long long)pageNumberForLine:(unsigned long long)arg1;
- (unsigned long long)lineCount;
- (long long)indexOfFirstLineOnPage:(unsigned long long)arg1;
- (void)clearCache;
- (void)buildModel:(struct CGPDFDocument *)arg1;
- (void)buildModel:(struct CGPDFDocument *)arg1 pageRange:(struct _NSRange)arg2;
- (void)dealloc;
- (id)initWithDocument:(struct CGPDFDocument *)arg1 withPageRange:(struct _NSRange)arg2;
- (id)initWithDocument:(struct CGPDFDocument *)arg1;

@end

