//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface UIView (CameraKit)
+ (double)cam_setHiddenAnimationDuration;
- (void)cam_setHidden:(BOOL)arg1 delay:(double)arg2 animated:(BOOL)arg3;
- (void)cam_setHidden:(BOOL)arg1 animated:(BOOL)arg2;
- (BOOL)cam_isOnScreen:(id)arg1;
@end

