/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

// Not exported
@interface SLGuaranteedRemoteCall : NSObject
{
    id _block;
    id _proxy;
}

@property(retain) id proxy; // @synthesize proxy=_proxy;
@property(copy) id block; // @synthesize block=_block;
- (void).cxx_destruct;

@end

