//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIKBHandwritingView;

__attribute__((visibility("hidden")))
@interface UIKBHandwritingStrokeView : UIView
{
    UIKBHandwritingView *_keyView;
}

@property(retain, nonatomic) UIKBHandwritingView *keyView; // @synthesize keyView=_keyView;
- (void)drawRect:(struct CGRect)arg1;
- (void)dealloc;

@end

