//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_UIRemoteViewController.h"

#import "SBUIRemoteAlertHostInterface.h"

@class NSString;

@interface _SBRemoteAlertHostViewController : _UIRemoteViewController <SBUIRemoteAlertHostInterface>
{
    id <_SBRemoteAlertHostViewControllerDelegate> _delegate;
    NSString *_serviceClassName;
}

+ (id)serviceViewControllerInterface;
+ (id)exportedInterface;
@property(copy, nonatomic) NSString *serviceClassName; // @synthesize serviceClassName=_serviceClassName;
@property(nonatomic) id <_SBRemoteAlertHostViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)viewServiceDidTerminateWithError:(id)arg1;
- (void)dismiss;
- (void)setAllowsBanners:(_Bool)arg1;
- (id)description;

@end

