//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SBAlertManagerObserverWrapper : NSObject
{
    id <SBAlertManagerObserver> _observer;
    CDStruct_b4247377 _flags;
}

- (id)initWithObserver:(id)arg1 flags:(CDStruct_b4247377)arg2;

@end

