//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SFAirDropDiscoveryController, UIActionSheet;

@protocol SFAirDropDiscoveryActionSheetDelegate <NSObject>

@optional
- (void)discoveryController:(SFAirDropDiscoveryController *)arg1 actionSheetDidDismiss:(UIActionSheet *)arg2;
- (void)discoveryController:(SFAirDropDiscoveryController *)arg1 actionSheetWillDismiss:(UIActionSheet *)arg2;
@end

