//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <OfficeImport/EDReference.h>

__attribute__((visibility("hidden")))
@interface EDSheetReference : EDReference
{
    unsigned int mSheetIndex;
}

+ (id)referenceWithSheetIndex:(unsigned int)arg1 firstRow:(int)arg2 lastRow:(int)arg3 firstColumn:(int)arg4 lastColumn:(int)arg5;
- (void)unionWithReference:(id)arg1;
- (_Bool)fullyAdjacentToReference:(id)arg1;
- (unsigned int)sheetIndex;
- (_Bool)isSheedIndexValid;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (BOOL)isEqualToTableReference:(id)arg1;
- (id)initWithSheetIndex:(unsigned int)arg1 firstRow:(int)arg2 lastRow:(int)arg3 firstColumn:(int)arg4 lastColumn:(int)arg5;
- (id)init;

@end

