/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface OABShapeProperties : NSObject
{
}

+ (id)targetColorWithSourceColor:(struct EshColor)arg1 alpha:(float)arg2 colorPropertiesManager:(id)arg3 colorPalette:(id)arg4;

@end

