//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface EKDirectoryRecord : NSObject
{
    NSString *_displayName;
    NSString *_preferredAddress;
}

@property(retain, nonatomic) NSString *preferredAddress; // @synthesize preferredAddress=_preferredAddress;
@property(retain, nonatomic) NSString *displayName; // @synthesize displayName=_displayName;
- (id)description;

@end

