/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <EventKit/EKPersistentObject.h>

#import "NSCopying-Protocol.h"

@class EKPersistentLocation, NSData, NSDate, NSString, NSTimeZone;

@interface EKPersistentAlarm : EKPersistentObject <NSCopying>
{
}

+ (id)relations;
- (BOOL)validate:(id *)arg1;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(copy, nonatomic) EKPersistentLocation *location;
@property(nonatomic) int proximity;
- (void)setOwner:(id)arg1;
- (id)owner;
@property(copy, nonatomic) NSString *externalID;
@property(copy, nonatomic) NSData *externalData;
@property(nonatomic) int alarmType;
@property(copy, nonatomic) NSTimeZone *timeZone;
@property(readonly, nonatomic) BOOL isAbsolute;
@property(copy, nonatomic) NSDate *absoluteDate;
@property(nonatomic) double relativeOffset;
@property(readonly, nonatomic) NSString *UUID;
- (int)entityType;
- (id)init;

@end

