//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@interface TPStarkInCallHardPauseButton : UIButton
{
    id <TPStarkHardPauseButtonDelegate> _delegate;
}

@property id <TPStarkHardPauseButtonDelegate> delegate; // @synthesize delegate=_delegate;
- (void)hardPauseControllerChangedNotification:(id)arg1;
- (void)updateHardPauseButtonState;
- (void)hardPausePressed;
- (void)setHighlighted:(BOOL)arg1;
- (void)setHidden:(BOOL)arg1;
- (void)dealloc;
- (id)init;

@end

