/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIView.h"

@class TPButton, TPWell;

@interface TPWellButtonView : UIView
{
    TPButton *_button;
    TPWell *_well;
}

@property(retain, nonatomic) TPButton *button; // @synthesize button=_button;
- (void)dealloc;
- (id)initWithTitle:(id)arg1 icon:(id)arg2 color:(int)arg3 frame:(struct CGRect)arg4;

@end

