//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <DataDetectorsUI/DDAction.h>

#import "EKEventEditViewDelegate.h"

@class NSString;

@interface DDCreateEventAction : DDAction <EKEventEditViewDelegate>
{
}

- (void)prepareViewControllerForActionController:(id)arg1;
- (void)eventEditViewController:(id)arg1 didCompleteWithAction:(int)arg2;
- (int)interactionType;
- (id)localizedName;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

