//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <iWorkImport/TSPObject.h>

#import "TPHeaderFooterProvider.h"
#import "TPMasterDrawableProvider.h"
#import "TSKDocumentObject.h"
#import "TSKModel.h"
#import "TSPCopying.h"

@class NSArray, NSMutableArray, TPDocumentRoot, TPSection, TSWPStorage;

__attribute__((visibility("hidden")))
@interface TPPageMaster : TSPObject <TPHeaderFooterProvider, TPMasterDrawableProvider, TSKDocumentObject, TSKModel, TSPCopying>
{
    TPDocumentRoot *_documentRoot;
    TPSection *_section;
    TSWPStorage *_headerFooters[2][3];
    NSMutableArray *_masterDrawables;
}

@property(nonatomic) TPSection *section; // @synthesize section=_section;
- (id)description;
- (void)p_makeMasterDrawablesPerformSelector:(SEL)arg1 withStylesheet:(id)arg2 withMapper:(id)arg3;
- (void)p_makeMasterDrawablesPerformSelector:(SEL)arg1 documentRoot:(id)arg2;
- (void)p_makeMasterDrawablesPerformSelector:(SEL)arg1 documentRoot:(id)arg2 context:(id)arg3;
- (void)p_makeHeadersFootersPerformSelector:(SEL)arg1 documentRoot:(id)arg2;
- (void)p_makeHeadersFootersPerformSelector:(SEL)arg1 documentRoot:(id)arg2 context:(id)arg3;
- (void)p_makeHeadersFootersPerformSelector:(SEL)arg1 withStylesheet:(id)arg2 withMapper:(id)arg3;
- (void)i_createHeadersFooters:(int)arg1 stylesheet:(id)arg2 paragraphStyle:(id)arg3 context:(id)arg4 mayAlreadyExist:(BOOL)arg5;
- (int)p_headerFragmentIndexForTabIndex:(unsigned int)arg1 paragraphStyle:(id)arg2 bodyWidth:(float)arg3;
- (void)p_splitHeaderFooterByTabs:(id)arg1 storages:(id *)arg2 dolcContext:(id)arg3 bodyWidth:(float)arg4;
- (void)p_filterParagraphStylesOnHeaderFooterStorage:(id)arg1 index:(int)arg2 stylesheet:(id)arg3;
- (id)p_headerAndFooterStorages;
- (void)i_copyHeadersAndFootersFrom:(id)arg1 dolcContext:(id)arg2;
- (void)i_importHeaderFooter:(id)arg1 headerType:(int)arg2 dolcContext:(id)arg3 splitHeaders:(BOOL)arg4;
- (void)i_splitHeaderFooter:(id)arg1 storages:(id *)arg2 dolcContext:(id)arg3 bodyWidth:(float)arg4;
- (void)i_ensureHeaderFooterStoragesExistWithStylesheet:(id)arg1 paragraphStyle:(id)arg2 context:(id)arg3;
- (void)i_addMasterDrawable:(id)arg1;
- (void)i_setHeaderFooter:(int)arg1 storage:(id)arg2 fragmentIndex:(int)arg3;
- (id)childEnumerator;
- (void)wasRemovedFromDocumentRoot:(id)arg1;
- (void)willBeRemovedFromDocumentRoot:(id)arg1;
- (void)wasAddedToDocumentRoot:(id)arg1 context:(id)arg2;
- (void)willBeAddedToDocumentRoot:(id)arg1 context:(id)arg2;
- (void)adoptStylesheet:(id)arg1 withMapper:(id)arg2;
- (void)setParentStorage:(id)arg1;
- (id)headerFooterFragmentEnumerator;
- (int)headerFragmentIndexForModel:(id)arg1;
- (int)headerFooterTypeForModel:(id)arg1;
- (BOOL)isHeaderFooterEmpty:(int)arg1 fragmentAtIndex:(int)arg2;
- (BOOL)isHeaderFooterEmpty:(int)arg1;
- (id)headerFooter:(int)arg1 fragmentAtIndex:(int)arg2;
- (BOOL)usesSingleHeaderFooter;
- (float)footerHeight;
- (float)headerHeight;
- (float)pHeightOfHeaderFooter:(int)arg1;
- (void)removeMasterDrawable:(id)arg1 suppressDOLC:(BOOL)arg2;
- (void)addMasterDrawables:(id)arg1 atIndex:(unsigned int)arg2 insertContext:(id)arg3 suppressDOLC:(BOOL)arg4;
- (void)addMasterDrawable:(id)arg1 atIndex:(unsigned int)arg2 insertContext:(id)arg3 suppressDOLC:(BOOL)arg4;
- (unsigned int)indexOfMasterDrawable:(id)arg1;
- (id)masterDrawablesSortedByZOrder:(id)arg1;
@property(readonly, nonatomic) NSArray *masterDrawables;
- (unsigned int)countOfMasterDrawables;
- (BOOL)ownsModelObject:(id)arg1;
- (id)copyWithContext:(id)arg1;
- (void)saveToArchiver:(id)arg1;
- (void)dealloc;
- (id)initFromUnarchiver:(id)arg1;
- (void)i_setDocumentRoot:(id)arg1;
- (id)initWithSection:(id)arg1;
- (id)getMergedHeaderFooter:(int)arg1;
- (BOOL)pAppendHeaderFooterFragment:(id)arg1 paragraph:(unsigned int)arg2 toCompositHeaderFooter:(id)arg3 segment:(unsigned int)arg4 lastSegmentInserted:(unsigned int)arg5 themeParStyle:(id)arg6 otherHFStyles:(id)arg7;
- (id)pHFParagraphStyleWithPropertiesFromStyle:(id)arg1 baseStyle:(id)arg2 otherHFStyles:(id)arg3;
- (void)pApplyParagraphStyle:(id)arg1 toHFFragment:(id)arg2;

@end

