//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class TSDGLShader;

__attribute__((visibility("hidden")))
@interface TSDGLEdgeDistanceFieldMorphEffect : NSObject
{
    BOOL _didTeardown;
    struct CGSize _outgoingTextureSize;
    struct CGSize _incomingTextureSize;
    struct CGRect _outgoingTextBounds;
    struct CGRect _incomingTextBounds;
    struct CGPoint _skewAngleOffsetX;
    BOOL _didSetupSkewAngleOffsetX;
    BOOL _isTextStyleIdenticalExceptSize;
    unsigned int _outgoingTextureName;
    unsigned int _incomingTextureName;
    TSDGLShader *_shader;
}

@property(nonatomic) BOOL isTextStyleIdenticalExceptSize; // @synthesize isTextStyleIdenticalExceptSize=_isTextStyleIdenticalExceptSize;
@property(readonly, nonatomic) TSDGLShader *shader; // @synthesize shader=_shader;
@property(readonly, nonatomic) unsigned int incomingTextureName; // @synthesize incomingTextureName=_incomingTextureName;
@property(readonly, nonatomic) unsigned int outgoingTextureName; // @synthesize outgoingTextureName=_outgoingTextureName;
- (void)setupShaderWithMorphPercent:(float)arg1 MVPMatrix:(struct CATransform3D)arg2 generateTextureMatrices:(BOOL)arg3;
- (void)setupShaderWithMorphPercent:(float)arg1 MVPMatrix:(struct CATransform3D)arg2 outgoingTextureMatrix:(struct CGAffineTransform)arg3 incomingTextureMatrix:(struct CGAffineTransform)arg4;
- (struct CGPoint)textureMatchingSkewAngleOffsetX;
- (struct CGAffineTransform)p_affineTransformConvertingRect:(struct CGRect)arg1 intoRect:(struct CGRect)arg2 atPercent:(float)arg3;
- (struct CGAffineTransform)p_affineTransformWithSkewAngleOffsetX:(struct CGPoint)arg1 textureSize:(struct CGSize)arg2;
- (float)p_errorFromApplyingSkewAngleOffsetX:(struct CGPoint)arg1 toOutgoingScanlines:(float *)arg2 incomingScanlines:(float *)arg3 samples:(unsigned int)arg4;
- (void)p_fillScanlineLocations:(float *)arg1 samples:(unsigned int)arg2 fromTexture:(unsigned int)arg3 textureSize:(struct CGSize)arg4;
- (struct CGRect)p_actualPixelBoundsOfTexturedRectangle:(id)arg1;
- (struct CGContext *)newContextFromTexture:(id)arg1;
- (void)teardown;
- (void)dealloc;
- (id)initWithOutgoingTextureName:(unsigned int)arg1 outgoingTextureSize:(struct CGSize)arg2 outgoingTextBounds:(struct CGRect)arg3 outgoingColor:(CDStruct_f2e236b6)arg4 incomingTextureName:(unsigned int)arg5 incomingTextureSize:(struct CGSize)arg6 incomingTextBounds:(struct CGRect)arg7 incomingColor:(CDStruct_f2e236b6)arg8;
- (id)initWithOutgoingTR:(id)arg1 incomingTR:(id)arg2;

@end

