/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <OfficeImport/CMMapper.h>

@class WDParagraph, WDParagraphProperties, WMParagraphStyle;

@interface WMParagraphStyleMapper : CMMapper
{
    WDParagraphProperties *wdParaProperties;
    WDParagraph *wdParagraph;
    WMParagraphStyle *mStyle;
}

- (void)mapAt:(id)arg1 withState:(id)arg2;
- (void)mapListStyleAt:(id)arg1 state:(id)arg2;
- (void)destyleEmptyParagraph;
- (BOOL)isListItem;
- (void)dealloc;
- (id)initWithWDParagraph:(id)arg1 parent:(id)arg2 isInTextFrame:(BOOL)arg3;
- (void)mapBulletAt:(id)arg1 forLevel:(id)arg2 forIndex:(int)arg3 listState:(id)arg4 isOutline:(BOOL)arg5;
- (id)bulletLabelAtLevel:(id)arg1 forIndex:(int)arg2 bulletFormat:(int)arg3 listState:(id)arg4;
- (id)labelStringWithGap:(id)arg1;
- (_Bool)checkListId:(int)arg1 level:(int)arg2;

@end

