/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "SBUIMainScreenAnimationController.h"

@class UIView;

@interface SBAppToAppTransitionController : SBUIMainScreenAnimationController
{
    UIView *_transitionView;
    UIView *_transformContainer;
    UIView *_fromAppContextHostView;
    UIView *_fromView;
    UIView *_toView;
    int _fromOrientation;
    BOOL _fromNC;
    BOOL _fromCC;
    BOOL _fromAssistant;
    BOOL _requiresHostView;
}

- (void)_rotateViewIfNecessary:(id)arg1 inverted:(BOOL)arg2;
- (void)_kickOffAnimation;
- (void)_setToView:(id)arg1;
- (void)_setFromView:(id)arg1;
- (int)_springBoardOrientationDuringAppLaunch;
- (void)_cleanupAnimation;
- (void)_startAnimation;
- (void)_prepareAnimation;
- (void)_setHidden:(BOOL)arg1;
- (id)_animationProgressDependency;
- (BOOL)_animationShouldStart;
- (void)dealloc;
- (id)initWithActivatingApp:(id)arg1 deactivatingApp:(id)arg2;
- (id)_getTransitionWindow;

@end

