/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UITableViewCell.h"

#import "ABGroupWrapperDelegate-Protocol.h"

@class ABGroupWrapper;

@interface ABGroupTableCell : UITableViewCell <ABGroupWrapperDelegate>
{
    ABGroupWrapper *_groupWrapper;
}

@property(retain, nonatomic) ABGroupWrapper *groupWrapper; // @synthesize groupWrapper=_groupWrapper;
- (void)groupWrapper:(id)arg1 didBecomeSelected:(BOOL)arg2;
- (void)updateFromGroupWrapper;
- (void)dealloc;

@end

