/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol ABPersonTabsLayoutManager <NSObject>
- (void)moveContentSwitchingTabsAboveView:(id)arg1 inScrollView:(id)arg2;
- (void)didChangeContentOffset:(struct CGPoint)arg1 inScrollView:(id)arg2;
- (void)repositionContentSwitchingTabs;
- (double)heightForHeaderAndContentSwitchingTabs;
@end

