//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BSMutableSettings;

@interface FBSSceneSettingsDiffInspector : NSObject
{
    BSMutableSettings *_observerInfo;
    BOOL _iteratingObservers;
}

- (id)description;
- (void)_addObserver:(id)arg1 forSetting:(unsigned int)arg2 inInfo:(id)arg3;
- (void)observeOtherSetting:(unsigned int)arg1 withBlock:(CDUnknownBlockType)arg2;
- (void)observeOcclusionsWithBlock:(CDUnknownBlockType)arg1;
- (void)observeIsBackgroundedWithBlock:(CDUnknownBlockType)arg1;
- (void)observeInterfaceOrientationWithBlock:(CDUnknownBlockType)arg1;
- (void)observeLevelWithBlock:(CDUnknownBlockType)arg1;
- (void)observeFrameWithBlock:(CDUnknownBlockType)arg1;
- (void)observeClassWithBlock:(CDUnknownBlockType)arg1;
- (void)removeAllObservers;
- (void)inspectDiff:(id)arg1 withContext:(void *)arg2;
- (void)dealloc;
- (id)init;

@end

