/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIView.h"

@class NSDate, UIColor, UILabel;

@interface SBUILockScreenDateView : UIView
{
    UILabel *_timeLabel;
    UILabel *_dateLabel;
    float _dateAlpha;
    NSDate *_date;
    id <SBUILockScreenDateFormatter> _formatter;
    UIColor *_textColor;
    float _dateAlphaPercentage;
}

+ (float)defaultHeight;
@property(nonatomic) float dateAlphaPercentage; // @synthesize dateAlphaPercentage=_dateAlphaPercentage;
@property(retain, nonatomic) UIColor *textColor; // @synthesize textColor=_textColor;
@property(retain, nonatomic) id <SBUILockScreenDateFormatter> formatter; // @synthesize formatter=_formatter;
@property(retain, nonatomic) NSDate *date; // @synthesize date=_date;
- (float)_dateBaselineOffsetFromTime;
- (id)_dateFont;
- (id)_timeFont;
- (void)_layoutTimeLabel;
- (void)_layoutDateLabel;
- (void)layoutSubviews;
- (float)dateBaselineOffsetFromOrigin;
- (float)timeBaselineOffsetFromOrigin;
- (void)updateFormat;
- (void)setContentAlpha:(float)arg1 withDateVisible:(BOOL)arg2;
@property(nonatomic, getter=isDateHidden) BOOL dateHidden;
- (void)_setDateAlpha:(float)arg1;
- (void)_addDateLabel;
- (void)_addTimeLabel;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

