//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "EKEditItemViewControllerProtocol.h"

@class NSString, UITextView;

__attribute__((visibility("hidden")))
@interface EKEventDetailExtendedNotesViewController : UIViewController <EKEditItemViewControllerProtocol>
{
    UITextView *_textView;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *notes;
- (id)_textView;
- (unsigned int)supportedInterfaceOrientations;
- (void)loadView;
- (id)init;

// Remaining properties
@property(nonatomic) __weak id <EKEditItemViewControllerDelegate> editDelegate;
@property(nonatomic) BOOL editItemShouldBeAskedForInjectableViewController;
@property(nonatomic) BOOL presentModally;

@end

