//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableSet, NSUbiquitousKeyValueStore;

@interface SGSuggestHistory : NSObject
{
    NSUbiquitousKeyValueStore *_backingKVStore;
    NSMutableSet *_eventHashes;
    NSMutableSet *_contactHashes;
    NSMutableSet *_dontUpdate;
    struct _opaque_pthread_mutex_t _lock;
}

+ (void)reset;
+ (id)hashesForEvent:(id)arg1;
+ (id)deviceSalt;
+ (id)identitySalt;
+ (id)sharedSuggestHistory;
- (void).cxx_destruct;
- (void)rejectFieldValuesForStorageEvent:(id)arg1;
- (void)addFieldValues:(id)arg1 forStorageEvent:(id)arg2;
- (BOOL)hasStorageEventWithRejectedFields:(id)arg1;
- (BOOL)hasStorageEvent:(id)arg1;
- (BOOL)hasEventWithRejectedFields:(id)arg1;
- (BOOL)hasFieldValues:(id)arg1 forStorageEvent:(id)arg2;
- (BOOL)hasFieldValues:(id)arg1 forEvent:(id)arg2;
- (BOOL)hasContact:(id)arg1 usingStore:(id)arg2;
- (BOOL)hasContactDetail:(id)arg1 forContact:(id)arg2 usingStore:(id)arg3;
- (BOOL)isValidSuggestion:(id)arg1;
- (BOOL)isUpdatableEvent:(id)arg1;
- (BOOL)isUpdatableContact:(id)arg1;
- (BOOL)hasEvent:(id)arg1;
- (BOOL)hasContact:(id)arg1;
- (void)rejectEvent:(id)arg1;
- (void)confirmEvent:(id)arg1;
- (void)rejectContact:(id)arg1;
- (void)handleSyncedDataChanged:(id)arg1;
- (void)reset;
- (id)hashesForContact:(id)arg1;
- (id)keysForContact:(id)arg1;
- (void)pushAll;
- (void)setInternalStateAccordingToKVS;
- (void)pushDontUpdate;
- (void)pushContacts;
- (void)pushEvents;
- (id)description;
- (void)dealloc;
- (id)setForKey:(id)arg1;
- (id)deviceSalt;
- (id)identitySalt;
- (id)init;

@end

