//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UILabel, _HKEmergencyContact;

@interface _EmergencyCardContactCell : UITableViewCell
{
    UILabel *_relationshipLabel;
    UILabel *_nameLabel;
    UILabel *_phoneNumberLabel;
    _HKEmergencyContact *_contact;
}

@property(retain, nonatomic) _HKEmergencyContact *contact; // @synthesize contact=_contact;
- (void).cxx_destruct;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

