/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "SSXPCCoding-Protocol.h"

@class NSDictionary, NSString;

@interface SSRemoteNotification : NSObject <SSXPCCoding>
{
    NSDictionary *_userInfo;
}

- (id)_valueForAlertKey:(id)arg1;
- (id)initWithXPCEncoding:(id)arg1;
- (id)copyXPCEncoding;
@property(readonly, nonatomic) NSDictionary *notificationUserInfo;
- (id)valueForKey:(id)arg1;
@property(readonly, nonatomic) NSString *soundFileName;
@property(readonly, nonatomic) id badgeValue;
@property(readonly, nonatomic) NSString *alertTitleString;
@property(readonly, nonatomic) NSString *alertOKString;
@property(readonly, nonatomic) NSString *alertCancelString;
@property(readonly, nonatomic) NSString *alertBodyString;
@property(readonly, nonatomic) int actionType;
- (void)dealloc;
- (id)initWithNotificationUserInfo:(id)arg1;

@end

