/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <AccountsUI/ACUIViewController.h>

@class ACAccount, NSArray, NSMutableArray, NSMutableDictionary, NSString, PSSpecifier;

@interface ACUIDataclassConfigurationViewController : ACUIViewController
{
    _Bool _forceMailSetup;
    NSMutableArray *_dirtyDataclassCells;
    NSString *_accountIdentifier;
    NSMutableDictionary *_allDesiredDataclassActions;
    _Bool _isMergingSyncData;
    PSSpecifier *_deleteButtonSpecifier;
    PSSpecifier *_accountSummaryCellSpecifier;
    NSArray *_dataclassSpecifiers;
    NSArray *_otherSpecifiers;
    _Bool _didShowDataclassActionPickerDuringRemoval;
    _Bool _firstTimeSetup;
    _Bool _shouldShowDeleteAccountButton;
    _Bool _shouldEnableAccountSummaryCell;
    _Bool _isMailSetupForced;
    NSArray *_preEnabledDataclasses;
    ACAccount *_account;
    PSSpecifier *_dataclassGroupSpecifier;
}

+ (_Bool)shouldPresentAsModalSheet;
@property(nonatomic) _Bool isMailSetupForced; // @synthesize isMailSetupForced=_isMailSetupForced;
@property(nonatomic) _Bool shouldEnableAccountSummaryCell; // @synthesize shouldEnableAccountSummaryCell=_shouldEnableAccountSummaryCell;
@property(nonatomic) _Bool shouldShowDeleteAccountButton; // @synthesize shouldShowDeleteAccountButton=_shouldShowDeleteAccountButton;
@property(nonatomic) __weak PSSpecifier *dataclassGroupSpecifier; // @synthesize dataclassGroupSpecifier=_dataclassGroupSpecifier;
@property(retain, nonatomic) ACAccount *account; // @synthesize account=_account;
@property(copy, nonatomic) NSArray *preEnabledDataclasses; // @synthesize preEnabledDataclasses=_preEnabledDataclasses;
@property(nonatomic, getter=isFirstTimeSetup) _Bool firstTimeSetup; // @synthesize firstTimeSetup=_firstTimeSetup;
- (void).cxx_destruct;
- (_Bool)_confirmDeleteLocalDataForDataclasses:(id)arg1;
- (_Bool)_confirmKeepLocalDataForDataclasses:(id)arg1;
- (id)_activityInProgressTextForDataclass:(id)arg1 isBeingEnabled:(_Bool)arg2;
- (void)hideActivityInProgressUIWithDelay:(double)arg1;
- (void)_showDelayedActivityInProgressUIWithMessage:(id)arg1;
- (void)operationsHelper:(id)arg1 didRemoveAccount:(id)arg2 withSuccess:(_Bool)arg3 error:(id)arg4;
- (void)operationsHelper:(id)arg1 willRemoveAccount:(id)arg2;
- (_Bool)_promptUserToConfirmAccountDeletion;
- (_Bool)operationsHelper:(id)arg1 shouldRemoveAccount:(id)arg2;
- (void)deleteButtonTapped:(id)arg1;
- (void)appendDeleteAccountButton;
- (_Bool)_isShowingDeleteAccountButton;
- (void)_notifyRootControllerOfAccountSetupCompletion;
- (void)operationsHelper:(id)arg1 didSaveAccount:(id)arg2 withSuccess:(_Bool)arg3 error:(id)arg4;
- (id)operationsHelper:(id)arg1 desiredDataclassActionFromPicker:(id)arg2;
- (void)operationsHelper:(id)arg1 willSaveAccount:(id)arg2;
- (id)_accountIdentifier;
- (id)_orderDataclassList:(id)arg1;
- (void)_setDataclass:(id)arg1 enabled:(_Bool)arg2;
- (void)setDataclass:(id)arg1 enabled:(_Bool)arg2;
- (_Bool)shouldAutomaticallyTryEnablingDataclassDuringSetup:(id)arg1;
- (void)_enableAllProvisionedDataclassesWithoutRequringUserInteraction;
- (void)resetDirtyDataclassSwitchCells;
- (void)_markDataclassSwitchCellAsDirty:(id)arg1;
- (void)dataclassSwitchStateDidChange:(id)arg1 withSpecifier:(id)arg2;
- (id)dataclassSwitchStateForSpecifier:(id)arg1;
- (void)reloadDynamicSpecifiersWithAnimation:(_Bool)arg1;
- (id)otherSpecifiers;
- (id)specifierForDataclass:(id)arg1;
- (_Bool)shouldShowSpecifierForDataclass:(id)arg1;
- (id)_specifiersForDataclasses:(id)arg1;
- (id)_specifierForAccountSummaryCell;
- (id)specifiers;
- (_Bool)shouldVerifyBeforeAccountSave;
- (void)cancelButtonTapped:(id)arg1;
- (void)doneButtonTapped:(id)arg1;
- (id)_navigationTitle;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (long long)deleteButtonIndex;
- (id)valueForAccountSummaryCell;
- (id)displayedShortAccountTypeString;
- (Class)accountInfoControllerClass;
- (id)displayedAccountTypeString;
- (void)forceMailSetup;
- (id)init;

@end

