//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSError, NSURL, QLPreviewItemAVState, QLPreviewItemProxy;

@protocol QLRemotePreviewContentProxyProtocol <NSObject>
- (void)_didExitFullScreen;
- (void)_willEnterFullScreenWithContext:(NSDictionary *)arg1;
- (void)_setAVState:(QLPreviewItemAVState *)arg1 forPreviewItem:(QLPreviewItemProxy *)arg2;
- (void)_previewContentControllerDidLoadItem:(QLPreviewItemProxy *)arg1 atIndex:(int)arg2 withError:(NSError *)arg3;
- (void)_previewContentControllerReceivedTapOnURL:(NSURL *)arg1;
- (void)_previewContentControllerDidMoveToItemAtIndex:(int)arg1;
- (void)_previewContentControllerWillMoveToItemAtIndex:(int)arg1;
- (void)_showContentsWasTappedInPreviewContentController;
- (void)_overlayWasTappedInPreviewContentController;
- (void)_contentWasTappedInPreviewContentController;
- (void)_previewContentControllerWillHideOverlayWithDuration:(double)arg1;
- (void)_previewContentControllerWillShowOverlayWithDuration:(double)arg1;
- (void)_previewContentControllerGetPreviewItemAtIndex:(int)arg1 sourceUUID:(int)arg2 handler:(void (^)(QLPreviewItemProxy *))arg3;
@end

