/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "APSConnectionDelegate-Protocol.h"

@class NSMutableDictionary, NSString;

@interface SBRemoteNotificationServer : NSObject <APSConnectionDelegate>
{
    NSMutableDictionary *_bundleIdentifiersToClients;
    NSMutableDictionary *_environmentsToConnections;
    NSString *_lastNotificationReceivedBundleIdentifier;
}

+ (id)sharedInstance;
- (id)_allPushRegisteredThirdPartyBundleIDs;
- (id)getMessageUserInfoForBundleIdentifier:(id)arg1;
- (void)setMessageUserInfo:(id)arg1 forBundleIdentifier:(id)arg2;
- (void)postSettingsChangedNotificationForBundleIdentifier:(id)arg1;
- (void)setSettingsTypes:(unsigned int)arg1 forBundleIdentifier:(id)arg2;
- (unsigned int)settingsEnabledTypesForBundleIdentifier:(id)arg1;
- (unsigned int)appEnabledTypesForBundleIdentifier:(id)arg1;
- (void)notePermissionAlertAcceptedTypes:(unsigned int)arg1 forBundleIdentifier:(id)arg2;
- (BOOL)hasRegisteredBundleIdentifiers;
- (void)setSystemwideEnabled:(BOOL)arg1;
- (BOOL)isSystemwideEnabled;
- (unsigned int)getEffectiveEnabledTypesForApplication:(id)arg1;
- (void)unregisterApplication:(id)arg1;
- (void)registerApplication:(id)arg1 forEnvironment:(id)arg2 withTypes:(unsigned int)arg3;
- (void)calculateTopics;
- (id)allSettingsEnabledTypeValues;
- (id)allAppEnabledTypeValues;
- (id)lastNotificationReceivedBundleIdentifier;
- (void)connection:(id)arg1 didReceiveIncomingMessage:(id)arg2;
- (void)noteApplicationFinishedLaunching:(id)arg1;
- (void)connection:(id)arg1 didReceivePublicToken:(id)arg2;
- (void)run;
- (void)dealloc;
- (id)init;

@end

