/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "GEODirectionsProvider.h"

#import "PBRequesterDelegate-Protocol.h"

@class GMMRequester;

@interface GMMGEODirectionsProvider : GEODirectionsProvider <PBRequesterDelegate>
{
    GMMRequester *_gmmRequester;
}

+ (id)providerHostname;
+ (unsigned short)providerID;
@property(retain, nonatomic) GMMRequester *gmmRequester; // @synthesize gmmRequester=_gmmRequester;
- (void)requesterDidCancel:(id)arg1;
- (void)requester:(id)arg1 didFailWithError:(id)arg2;
- (void)requesterDidFinish:(id)arg1;
- (void)_cleanupRequester;
- (void)cancelProviderRequest;
- (void)_sendGMMDirectionsRequest:(id)arg1;
- (void)startProviderWithRequest:(id)arg1;
- (void)dealloc;

@end

