//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <ITMLKit/IKViewElement.h>

@class IKHeaderElement, NSArray;

@interface IKSectionElement : IKViewElement
{
    NSArray *_items;
}

- (void).cxx_destruct;
@property(readonly, retain, nonatomic) NSArray *items;
@property(readonly, retain, nonatomic) IKHeaderElement *header;
- (id)applyUpdatesWithElement:(id)arg1;

@end

