/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iLifeSlideshow/MREffect.h>

@class MRCroppingSprite, MRImage, MRTextRenderer, NSArray, NSMutableArray, NSMutableDictionary;

@interface MREffectOrigamiTitle : MREffect
{
    MRTextRenderer *mText0Renderer;
    MRCroppingSprite *mText0Sprite;
    NSMutableArray *mText0Images;
    NSMutableArray *mText0Offsets;
    MRImage *mText0Image;
    unsigned char mLineWordCounts[3];
    NSMutableArray *mWordIndexForGlyph;
    NSArray *mPatchworkAtEnd;
    NSMutableDictionary *mSprites;
    struct CGSize mImageSize;
    int mWordCount;
}

- (id)patchworkAtTime:(double)arg1 inContext:(id)arg2 withArguments:(id)arg3;
- (void)renderBreakImage:(id)arg1 atProgress:(float)arg2 withKey:(id)arg3 inContext:(id)arg4 withArguments:(id)arg5 inRect:(struct CGRect)arg6 withAttributes:(id)arg7;
- (void)renderStillImage:(id)arg1 withKey:(id)arg2 inContext:(id)arg3 withArguments:(id)arg4 inRect:(struct CGRect)arg5 withAttributes:(id)arg6;
- (void)renderFallBreakImage:(id)arg1 atProgress:(float)arg2 inContext:(id)arg3 withArguments:(id)arg4 inRect:(struct CGRect)arg5 withAttributes:(id)arg6:(struct CGPoint *)arg7:(struct CGPoint)arg8;
- (void)renderFallImage:(id)arg1 atProgress:(float)arg2 inContext:(id)arg3 withArguments:(id)arg4 inRect:(struct CGRect)arg5 withAttributes:(id)arg6:(struct CGPoint *)arg7:(struct CGPoint)arg8;
- (void)renderFallImage:(id)arg1 atProgress:(float)arg2 strength:(float)arg3 inContext:(id)arg4 withArguments:(id)arg5 inRect:(struct CGRect)arg6 withAttributes:(id)arg7:(struct CGPoint *)arg8:(struct CGPoint)arg9;
- (BOOL)getVerticesCoordinates:(struct CGPoint (*)[4])arg1 withMatrix:(float [16])arg2 forElement:(id)arg3;
- (id)elementHitAtPoint:(struct CGPoint)arg1 withInverseMatrix:(float [16])arg2 localPoint:(struct CGPoint *)arg3;
- (void)renderTextEffectAtTime:(double)arg1 inContext:(id)arg2 withArguments:(id)arg3;
- (void)renderTitleEffectAtTime:(double)arg1 inContext:(id)arg2 withArguments:(id)arg3;
- (void)renderAtTime:(double)arg1 inContext:(id)arg2 withArguments:(id)arg3;
- (BOOL)isLoadedForTime:(double)arg1;
- (void)_cleanup;
- (id)init;
- (void)_unload;
- (int)_maxLinesForTextElement:(id)arg1;
- (struct CGSize)_maxSizeForTextElement:(id)arg1;
- (void)_loadForTime:(double)arg1 inContext:(id)arg2 withArguments:(id)arg3;

@end

