/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface MRGesturePanZoomRotation : NSObject
{
    double time;
    float x;
    float y;
    float deltaX;
    float deltaY;
    float scale;
    float rotation;
    float speedX;
    float speedY;
    float speedScale;
    float speedRotation;
    int direction;
}

@end

