/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <GameKit/GKAchievementViewControllerPrivate.h>

@class GKAchievementCompareHeaderSection, GKAchievementCompareViewSection, GKGameRecord, GKPlayer, NSArray, UIImage;

@interface GKAchievementCompareViewControllerPrivate : GKAchievementViewControllerPrivate
{
    GKPlayer *_friend;
    UIImage *_compositeCheckMark;
    GKGameRecord *_friendRecord;
    NSArray *_friendAchievements;
    GKAchievementCompareViewSection *_achievementCompareViewSection;
    GKAchievementCompareHeaderSection *_achievementCompareMeHeaderViewSection;
    GKAchievementCompareHeaderSection *_achievementCompareFriendHeaderViewSection;
}

@property(retain, nonatomic) GKAchievementCompareHeaderSection *achievementCompareFriendHeaderViewSection; // @synthesize achievementCompareFriendHeaderViewSection=_achievementCompareFriendHeaderViewSection;
@property(retain, nonatomic) GKAchievementCompareHeaderSection *achievementCompareMeHeaderViewSection; // @synthesize achievementCompareMeHeaderViewSection=_achievementCompareMeHeaderViewSection;
@property(retain, nonatomic) GKAchievementCompareViewSection *achievementCompareViewSection; // @synthesize achievementCompareViewSection=_achievementCompareViewSection;
@property(retain, nonatomic) UIImage *compositeCheckMark; // @synthesize compositeCheckMark=_compositeCheckMark;
@property(retain, nonatomic) NSArray *friendAchievements; // @synthesize friendAchievements=_friendAchievements;
@property(retain, nonatomic) GKGameRecord *friendRecord; // @synthesize friendRecord=_friendRecord;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (void)_gkResetContents;
- (void)_gkUpdateContentsWithCompletionHandlerAndError:(id)arg1;
- (BOOL)_gkShouldRefreshContentsForDataType:(unsigned int)arg1 userInfo:(id)arg2;
- (void)updateStatusWithError:(id)arg1;
- (void)dealloc;
- (void)viewDidLoad;
- (id)title;
- (void)playTapped;
- (id)initWithGameRecord:(id)arg1 friendRecord:(id)arg2;
- (void)setupSectionDataSource:(id)arg1;

@end

