/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIControl.h"

@class GKUITheme, UIColor, UIImage, UILabel;

@interface GKInviteButton : UIControl
{
    GKUITheme *_theme;
    int _buttonStyle;
    UILabel *_titleLabel;
    UIImage *_normalImage;
    UIColor *_normalTitleColor;
    UIColor *_normalShadowTitleColor;
    UIImage *_highlightImage;
    UIColor *_highlightTitleColor;
    UIColor *_highlightShadowTitleColor;
    struct UIEdgeInsets _titleEdgeInsets;
    float _mostlyInsideInset;
    BOOL _adjustsImageWhenHighlighted;
    id _representedObject;
}

@property(retain, nonatomic) id representedObject; // @synthesize representedObject=_representedObject;
@property(nonatomic) BOOL adjustsImageWhenHighlighted; // @synthesize adjustsImageWhenHighlighted=_adjustsImageWhenHighlighted;
@property(nonatomic) float mostlyInsideInset; // @synthesize mostlyInsideInset=_mostlyInsideInset;
@property(nonatomic) struct UIEdgeInsets titleEdgeInsets; // @synthesize titleEdgeInsets=_titleEdgeInsets;
@property(retain, nonatomic) UIColor *highlightTitleShadowColor; // @synthesize highlightTitleShadowColor=_highlightShadowTitleColor;
@property(retain, nonatomic) UIColor *highlightTitleColor; // @synthesize highlightTitleColor=_highlightTitleColor;
@property(retain, nonatomic) UIImage *highlightImage; // @synthesize highlightImage=_highlightImage;
@property(retain, nonatomic) UIColor *normalTitleShadowColor; // @synthesize normalTitleShadowColor=_normalShadowTitleColor;
@property(retain, nonatomic) UIColor *normalTitleColor; // @synthesize normalTitleColor=_normalTitleColor;
@property(retain, nonatomic) UIImage *normalImage; // @synthesize normalImage=_normalImage;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) int buttonStyle; // @synthesize buttonStyle=_buttonStyle;
@property(retain, nonatomic) GKUITheme *theme; // @synthesize theme=_theme;
- (unsigned long long)accessibilityTraits;
- (id)accessibilityLabel;
- (BOOL)isAccessibilityElement;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)layoutSubviews;
- (void)setHightlightShadowTitleColor:(id)arg1;
- (void)setHightlightTitleColor:(id)arg1;
- (void)setNormalShadowTitleColor:(id)arg1;
- (void)setHighlighted:(BOOL)arg1;
- (void)dealloc;
- (id)initWithTheme:(id)arg1;

@end

