//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class WebSecurityOriginPrivate;

@interface WebSecurityOrigin : NSObject
{
    WebSecurityOriginPrivate *_private;
    id <WebQuotaManager> _applicationCacheQuotaManager;
    id <WebQuotaManager> _databaseQuotaManager;
}

+ (id)webSecurityOriginFromDatabaseIdentifier:(id)arg1;
- (void)finalize;
- (void)dealloc;
- (BOOL)isEqual:(id)arg1;
- (unsigned short)port;
- (id)stringValue;
- (id)toString;
- (id)databaseIdentifier;
- (id)host;
- (id)protocol;
- (id)initWithURL:(id)arg1;
-     // Error parsing type: ^{SecurityOrigin={atomic<int>=Ai}{String={RefPtr<WTF::StringImpl>=^{StringImpl}}}{String={RefPtr<WTF::StringImpl>=^{StringImpl}}}{String={RefPtr<WTF::StringImpl>=^{StringImpl}}}{String={RefPtr<WTF::StringImpl>=^{StringImpl}}}SBBBBiBB}8@0:4, name: _core
-     // Error parsing type: @12@0:4^{SecurityOrigin={atomic<int>=Ai}{String={RefPtr<WTF::StringImpl>=^{StringImpl}}}{String={RefPtr<WTF::StringImpl>=^{StringImpl}}}{String={RefPtr<WTF::StringImpl>=^{StringImpl}}}{String={RefPtr<WTF::StringImpl>=^{StringImpl}}}SBBBBiBB}8, name: _initWithWebCoreSecurityOrigin:
- (id)databaseQuotaManager;
- (id)applicationCacheQuotaManager;
- (void)setQuota:(unsigned long long)arg1;
- (unsigned long long)quota;
- (unsigned long long)usage;

@end

