//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIImage.h>

@class NSArray;

__attribute__((visibility("hidden")))
@interface _UIAnimatedImage : UIImage
{
    NSArray *_images;
    double _duration;
}

+ (BOOL)supportsSecureCoding;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (id)_imageWithStylePresets:(id)arg1 withTintColor:(id)arg2;
- (id)_imageScaledToProportion:(float)arg1 interpolationQuality:(int)arg2;
- (id)_doubleBezeledImageWithExteriorShadowRed:(float)arg1 green:(float)arg2 blue:(float)arg3 alpha:(float)arg4 interiorShadowRed:(float)arg5 green:(float)arg6 blue:(float)arg7 alpha:(float)arg8 fillRed:(float)arg9 green:(float)arg10 blue:(float)arg11 alpha:(float)arg12;
- (id)_bezeledImageWithShadowRed:(float)arg1 green:(float)arg2 blue:(float)arg3 alpha:(float)arg4 fillRed:(float)arg5 green:(float)arg6 blue:(float)arg7 alpha:(float)arg8 drawShadow:(BOOL)arg9;
- (struct UIEdgeInsets)alignmentRectInsets;
- (void)_setAlignmentRectInsets:(struct UIEdgeInsets)arg1;
- (id)resizableImageWithCapInsets:(struct UIEdgeInsets)arg1 resizingMode:(int)arg2;
- (id)resizableImageWithCapInsets:(struct UIEdgeInsets)arg1;
- (void)_setAlwaysStretches:(BOOL)arg1;
- (BOOL)_isTiledWhenStretchedToSize:(struct CGSize)arg1;
- (BOOL)_isResizable;
- (struct CGRect)_contentRectInPixels;
- (struct CGRect)_contentStretchInPixels;
- (int)resizingMode;
- (struct UIEdgeInsets)capInsets;
- (double)duration;
- (id)images;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;
- (id)initWithImages:(id)arg1 duration:(double)arg2;
- (id)_initWithOtherImage:(id)arg1;
- (id)_unselectedTabBarItemImageWithTintColor:(id)arg1 metrics:(int)arg2 style:(int)arg3 forScreenScale:(float)arg4;
- (id)_selectedTabBarItemImageWithTintColor:(id)arg1 metrics:(int)arg2 style:(int)arg3 forScreenScale:(float)arg4;

@end

