//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, UICalloutBar;

@protocol UICalloutBarDelegate <NSObject>

@optional
- (void)calloutBar:(UICalloutBar *)arg1 didFinishAnimation:(NSDictionary *)arg2;
- (void)calloutBar:(UICalloutBar *)arg1 willStartAnimation:(NSDictionary *)arg2;
@end

