/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <UIKit/UIView.h>

#import "UICollectionViewDataSource-Protocol.h"
#import "UIKeyboardCandidateBarLayoutDelegate-Protocol.h"
#import "UIKeyboardCandidateList-Protocol.h"
#import "UIKeyboardCandidateListDelegate-Protocol.h"

@class NSArray, NSIndexPath, NSString, TIKeyboardCandidateResultSet, UICollectionView, UIImageView;

@interface UIKeyboardCandidateBar : UIView <UIKeyboardCandidateList, UIKeyboardCandidateListDelegate, UIKeyboardCandidateBarLayoutDelegate, UICollectionViewDataSource>
{
    BOOL _canExtend;
    BOOL _shouldSkipLayoutUntilScrollViewAnimationEnds;
    BOOL _didSkipLayout;
    NSString *_inlineText;
    UIImageView *_candidateMaskView;
    id <UIKeyboardCandidateBarDelegate> _delegate;
    id <UIKeyboardCandidateListDelegate> _candidateListDelegate;
    UICollectionView *_collectionView;
    TIKeyboardCandidateResultSet *_candidateResultSet;
    NSArray *_filteredCandidates;
    NSIndexPath *_dragStartNextPageIndexPath;
    NSIndexPath *_dragStartPreviousPageIndexPath;
    id _skippedSetCandidatesBlock;
    struct CGPoint _dragStartOffset;
}

+ (float)defaultCandidateWidth;
+ (float)candidateBarHeight;
@property(copy, nonatomic) id skippedSetCandidatesBlock; // @synthesize skippedSetCandidatesBlock=_skippedSetCandidatesBlock;
@property(nonatomic) BOOL didSkipLayout; // @synthesize didSkipLayout=_didSkipLayout;
@property(nonatomic) BOOL shouldSkipLayoutUntilScrollViewAnimationEnds; // @synthesize shouldSkipLayoutUntilScrollViewAnimationEnds=_shouldSkipLayoutUntilScrollViewAnimationEnds;
@property(copy, nonatomic) NSIndexPath *dragStartPreviousPageIndexPath; // @synthesize dragStartPreviousPageIndexPath=_dragStartPreviousPageIndexPath;
@property(copy, nonatomic) NSIndexPath *dragStartNextPageIndexPath; // @synthesize dragStartNextPageIndexPath=_dragStartNextPageIndexPath;
@property(nonatomic) struct CGPoint dragStartOffset; // @synthesize dragStartOffset=_dragStartOffset;
@property(nonatomic) BOOL canExtend; // @synthesize canExtend=_canExtend;
@property(retain, nonatomic) NSArray *filteredCandidates; // @synthesize filteredCandidates=_filteredCandidates;
@property(retain, nonatomic) TIKeyboardCandidateResultSet *candidateResultSet; // @synthesize candidateResultSet=_candidateResultSet;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(nonatomic) id <UIKeyboardCandidateListDelegate> candidateListDelegate; // @synthesize candidateListDelegate=_candidateListDelegate;
@property(nonatomic) id <UIKeyboardCandidateBarDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIImageView *candidateMaskView; // @synthesize candidateMaskView=_candidateMaskView;
@property(copy, nonatomic) NSString *inlineText; // @synthesize inlineText=_inlineText;
- (void)setFrame:(struct CGRect)arg1;
@property(readonly, nonatomic) TIKeyboardCandidateResultSet *candidates;
- (float)_emptySpaceForItemsToIndex:(unsigned int)arg1 inSection:(int)arg2;
- (struct CGSize)_sizeOfItemAtIndex:(unsigned int)arg1 inSection:(int)arg2;
- (id)_itemAtIndex:(unsigned int)arg1 inSection:(int)arg2;
- (unsigned int)_countOfItemsInSection:(int)arg1;
- (id)_indexPathForLastVisibleItem;
- (id)_indexPathForFirstVisibleItem;
- (id)_previousPageIndexPath;
- (id)_nextPageIndexPath;
- (void)_showPageAtIndexPath:(id)arg1;
- (void)_updateCanExtendState;
- (void)_stepSelectedCandidateInDirection:(BOOL)arg1;
- (void)_scrollToFirstCandidateInSection:(int)arg1 withAnimation:(BOOL)arg2;
- (void)_showCandidateAtIndex:(unsigned int)arg1 inSection:(int)arg2 scrollCellToVisible:(BOOL)arg3 animated:(BOOL)arg4;
- (void)_performSkippedLayoutIfNeeded;
- (BOOL)_showingInitiallyHiddenCandidates;
- (void)_reloadData;
- (void)_clearData;
- (void)candidateListShouldBeDismissed:(id)arg1;
- (void)candidateListSelectionDidChange:(id)arg1;
- (void)candidateListAcceptCandidate:(id)arg1;
- (void)revealHiddenCandidates;
- (id)keyboardBehaviors;
- (BOOL)hasCandidates;
- (unsigned int)count;
- (void)candidateAcceptedAtIndex:(unsigned int)arg1;
- (unsigned int)currentIndex;
- (id)currentCandidate;
- (BOOL)hasNextPage;
- (BOOL)hasPreviousPage;
- (void)showPreviousPage;
- (void)showNextPage;
- (void)showPreviousCandidate;
- (void)showNextCandidate;
- (void)showCandidateAtIndex:(unsigned int)arg1;
- (void)showCandidate:(id)arg1;
- (void)setUIKeyboardCandidateListDelegate:(id)arg1;
- (void)candidatesDidChange;
- (void)setCandidates:(id)arg1 inlineText:(id)arg2 inlineRect:(struct CGRect)arg3 maxX:(float)arg4 layout:(BOOL)arg5;
- (BOOL)isExtendedList;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (struct CGSize)sizeOfDummyItemForCollectionView:(id)arg1 layout:(id)arg2;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (int)collectionView:(id)arg1 numberOfItemsInSection:(int)arg2;
- (int)numberOfSectionsInCollectionView:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

