/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <RemoteUI/RUIElement.h>

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "UIWebViewDelegate-Protocol.h"

@class NSMutableArray, RUITableViewRow, UIDatePicker, UIPickerView, UITableView;

@interface RUITableView : RUIElement <UITableViewDataSource, UITableViewDelegate, UIWebViewDelegate>
{
    NSMutableArray *_sections;
    UITableView *_tableView;
    UIPickerView *_selectPicker;
    BOOL _showSelectPicker;
    UIDatePicker *_datePicker;
    BOOL _showDatePicker;
    RUITableViewRow *_defaultFirstResponderRow;
    BOOL _viewShrunk;
    id _delegate;
    BOOL _registeredForNotifications;
    float _lastLayoutWidth;
    float _fullscreenCellHeight;
    float _customMargin;
}

@property(retain, nonatomic) RUITableViewRow *defaultFirstResponderRow; // @synthesize defaultFirstResponderRow=_defaultFirstResponderRow;
@property(readonly, nonatomic) NSMutableArray *sections; // @synthesize sections=_sections;
- (void)rowIsFirstResponder:(id)arg1;
- (void)rowDidChange:(id)arg1;
- (void)rowDidEndEditing:(id)arg1;
- (id)sourceURLForRUITableViewRow;
- (BOOL)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(int)arg3;
- (void)_textChanged:(id)arg1;
- (void)textFieldStartedEditing:(id)arg1;
- (void)sectionActivatedButton:(id)arg1 attributes:(id)arg2;
- (void)sectionActivatedLink:(id)arg1 attributes:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(int)arg2 forRowAtIndexPath:(id)arg3;
- (BOOL)tableView:(id)arg1 shouldIndentWhileEditingRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)activateRowAtIndexPath:(id)arg1 animated:(BOOL)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
@property(readonly, nonatomic, getter=isShowingPicker) BOOL showingPicker;
- (struct CGRect)_selectPickerFrame;
- (float)marginForTableView:(id)arg1;
- (id)tableView:(id)arg1 viewForFooterInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForFooterInSection:(int)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (id)tableView:(id)arg1 titleForFooterInSection:(int)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)viewDidLayout;
- (void)automaticKeyboardDidHide:(id)arg1;
- (void)automaticKeyboardDidShow:(id)arg1;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)_setBottomInset:(float)arg1;
- (void)_clearPickers;
- (id)indexPathForRow:(id)arg1;
- (id)objectModelRowForIndexPath:(id)arg1;
- (void)populatePostbackDictionary:(id)arg1;
- (void)setCustomMargin:(float)arg1;
- (void)setDelegate:(id)arg1;
- (void)setAttributes:(id)arg1;
- (id)tableView;
- (void)dealloc;
- (void)_registerForNotifications:(BOOL)arg1;
- (id)init;

@end

