//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <RemoteUI/RUIElement.h>

#import "UIPickerViewDelegate.h"
#import "UITextFieldDelegate.h"

@class NSData, NSDate, NSDictionary, NSMutableArray, RemoteUITableViewCell, UISwitch, UIWebView, WebContainerView;

@interface RUITableViewRow : RUIElement <UIPickerViewDelegate, UITextFieldDelegate>
{
    RemoteUITableViewCell *_tableCell;
    id _delegate;
    NSMutableArray *_selectOptions;
    int _selectedRow;
    NSDate *_date;
    NSDate *_dateMax;
    NSDate *_dateMin;
    UISwitch *_switchControl;
    BOOL _rowInvalid;
    NSDictionary *_deleteAction;
    NSData *_data;
    UIWebView *_webView;
    WebContainerView *_webContainerView;
    float _cachedHeight;
    BOOL _configured;
    float _height;
}

+ (void)resetLocale;
+ (id)_formatterForMonthAndDay;
+ (id)_formatterForShortDate;
+ (id)_formatterForDateYMD;
+ (id)_timeZoneAdjustedDateFromDate:(id)arg1;
+ (void)initialize;
@property(nonatomic) BOOL configured; // @synthesize configured=_configured;
@property(nonatomic) float height; // @synthesize height=_height;
@property(retain, nonatomic) NSDate *dateMax; // @synthesize dateMax=_dateMax;
@property(retain, nonatomic) NSDate *dateMin; // @synthesize dateMin=_dateMin;
@property(retain, nonatomic) NSDate *date; // @synthesize date=_date;
@property(readonly, nonatomic) int selectedRow; // @synthesize selectedRow=_selectedRow;
@property(retain, nonatomic) NSData *data; // @synthesize data=_data;
@property(retain, nonatomic) NSDictionary *deleteAction; // @synthesize deleteAction=_deleteAction;
@property(nonatomic) BOOL rowInvalid; // @synthesize rowInvalid=_rowInvalid;
- (id)sourceURL;
- (BOOL)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (BOOL)textFieldShouldReturn:(id)arg1;
- (int)numberOfComponentsInPickerView:(id)arg1;
- (int)pickerView:(id)arg1 numberOfRowsInComponent:(int)arg2;
- (id)pickerView:(id)arg1 titleForRow:(int)arg2 forComponent:(int)arg3;
- (void)pickerView:(id)arg1 didSelectRow:(int)arg2 inComponent:(int)arg3;
- (void)_activate;
- (void)clearCachedHeight;
- (float)rowHeightWithMax:(float)arg1 peggedHeight:(float)arg2 tableView:(id)arg3 indexPath:(id)arg4;
- (void)_datePickerChanged:(id)arg1;
- (void)dealloc;
- (id)selectOptions;
- (void)populatePostbackDictionary:(id)arg1;
- (BOOL)supportsAutomaticSelection;
- (id)tableCell;
- (BOOL)loadAccessoryImage;
- (void)accessoryImageLoaded;
- (void)setImage:(id)arg1;
- (int)tableCellStyle;
- (Class)tableCellClass;
- (void)setAttributes:(id)arg1;
- (void)setDelegate:(id)arg1;

@end

