//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSXPCInterface.h"

@interface GKViewServiceInterface : NSXPCInterface
{
}

+ (void)_configureKVOTypes:(id)arg1;
+ (id)turnBasedServiceViewControllerInterface;
+ (id)turnBasedRemoteViewControllerInterface;
+ (id)matchmakerServiceViewControllerInterface;
+ (id)matchmakerRemoteViewControllerInterface;
+ (id)challengeIssueServiceViewControllerInterface;
+ (id)remoteChallengeIssueViewControllerInterface;
+ (id)serviceFriendRequestViewControllerInterface;
+ (id)remoteFriendRequestViewControllerInterface;
+ (id)signInServiceViewControllerInterface;
+ (id)remoteSignInViewControllerInterface;
+ (id)gameCenterServiceViewControllerInterface;
+ (id)gameCenterViewControllerInterface;
+ (id)serviceViewControllerInterface;
+ (id)remoteViewControllerInterface;

@end

