/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <CoreUI/CUICommonAssetStorage.h>

@interface CUICommonAssetStorage (CUIStructuredThemeStore_Debugging)
- (id)displayNameForPartID:(long long)arg1;
- (id)constantNameForPartID:(long long)arg1;
- (id)displayNameForElementID:(long long)arg1;
- (id)constantNameForElementID:(long long)arg1;
- (id)_displayNameForIdentifier:(unsigned int)arg1 fromDebugTree:(void *)arg2;
- (id)_constantNameForIdentifier:(unsigned int)arg1 fromDebugTree:(void *)arg2;
- (id)_dataForIdentifier:(unsigned int)arg1 fromDebugTree:(void *)arg2;
@end

