//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSData;

@protocol ABPeoplePickerHostViewControllerDelegate
- (BOOL)shouldContinueAfterSelectingPerson:(int)arg1 vcard:(NSData *)arg2 property:(int)arg3 identifier:(int)arg4;
- (BOOL)shouldContinueAfterSelectingPerson:(int)arg1 vcard:(NSData *)arg2;
- (void)didCancel;
@end

