/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <AirPortAssistant/StepByStepUIViewController_ExtendWireless_Config.h>

@interface StepByStepUIViewController_ExtendWired_Config : StepByStepUIViewController_ExtendWireless_Config
{
}

- (void)viewDidLoad;

@end

