//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SKUIGiftCharity, SKUIGiftConfiguration, SKUIGiftTheme;

@protocol SKUIGiftConfigurationObserver <NSObject>

@optional
- (void)giftConfigurationController:(SKUIGiftConfiguration *)arg1 didLoadLogoForCharity:(SKUIGiftCharity *)arg2;
- (void)giftConfigurationController:(SKUIGiftConfiguration *)arg1 didLoadImageForTheme:(SKUIGiftTheme *)arg2;
@end

