/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class CAContext, CALayer;

@interface PUIProgressWindow : NSObject
{
    CAContext *_context;
    struct CGSize _displaySize;
    float _displayScale;
    float _displayOrientation;
    float _currentProgress;
    float _level;
    struct CGImage *_appleLogo;
    double _progressXDelta;
    double _progressYDelta;
    double _progressWidth;
    CALayer *_progressLayer;
    _Bool _forceInverted;
    _Bool _inverted;
    _Bool _showsProgressBar;
}

- (void).cxx_destruct;
- (struct CGImage *)_createImageWithName:(const char *)arg1 scale:(int)arg2;
- (void)drawLayer:(id)arg1 inContext:(struct CGContext *)arg2;
- (void)_layoutScreen;
- (const char *)_productSuffix;
- (void)setProgressValue:(float)arg1;
- (void)setVisible:(_Bool)arg1;
- (void)_createContext;
- (void)dealloc;
- (id)initWithProgressBarVisibility:(_Bool)arg1 level:(float)arg2 forceInverted:(_Bool)arg3;
- (id)initWithProgressBarVisibility:(_Bool)arg1 level:(float)arg2;
- (id)initWithProgressBarVisibility:(_Bool)arg1;
- (id)init;

@end

