/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UISegmentedControl.h"

@class NSMutableDictionary;

@interface PLSegmentedControl : UISegmentedControl
{
    NSMutableDictionary *_tagMap;
}

- (void)removeSegmentAtIndex:(unsigned int)arg1 animated:(BOOL)arg2;
- (void)removeAllSegments;
- (void)insertSegmentWithImage:(id)arg1 atIndex:(unsigned int)arg2 animated:(BOOL)arg3;
- (void)insertSegmentWithTitle:(id)arg1 atIndex:(unsigned int)arg2 animated:(BOOL)arg3;
- (void)_incrementIndexesForTagsStartingAtIndex:(unsigned int)arg1;
@property(nonatomic) int selectedTag;
- (unsigned int)segmentIndexForTag:(unsigned int)arg1;
- (int)tagForSegmentAtIndex:(unsigned int)arg1;
- (void)setTag:(int)arg1 forSegmentAtIndex:(unsigned int)arg2;
- (void)dealloc;

@end

