//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ACAccount, NSData, NSString;

@interface ACRemoteDeviceMessage : NSObject
{
    NSString *_command;
    NSData *_data;
    ACAccount *_account;
}

@property(readonly, nonatomic) ACAccount *account; // @synthesize account=_account;
@property(readonly, nonatomic) NSData *data; // @synthesize data=_data;
@property(readonly, nonatomic) NSString *command; // @synthesize command=_command;
- (void).cxx_destruct;
- (id)initWithData:(id)arg1;
- (id)initWithCommand:(id)arg1 account:(id)arg2;
- (id)init;

@end

