//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIScrollView.h"

@interface UIScrollView (CKUtilities)
- (void)__ck_scrollToTop:(BOOL)arg1;
- (BOOL)__ck_isScrolledToTop;
- (struct CGPoint)__ck_scrollToTopContentOffset;
- (void)__ck_scrollToBottom:(BOOL)arg1;
- (BOOL)__ck_isScrolledToBottom;
- (struct CGPoint)__ck_scrollToBottomContentOffset;
- (struct CGSize)__ck_contentSize;
@end

