//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "RCCurrentRecordingViewControllerDelegate.h"

@class RCCurrentRecordingRemoteViewController, UIColor;

@interface RCCurrentRecordingViewController : UIViewController <RCCurrentRecordingViewControllerDelegate>
{
    BOOL _screenUpdatesDisabled;
    BOOL _isDisplayingLockscreenInterface;
    UIColor *_presentationBackgroundColor;
    UIColor *_waveformForegroundColor;
    RCCurrentRecordingRemoteViewController *_remoteViewController;
    id <RCCurrentRecordingViewControllerDelegate> _delegate;
}

+ (Class)remoteViewControllerClass;
+ (id)serviceViewControllerClassName;
@property(nonatomic) __weak id <RCCurrentRecordingViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_failedToBecomeReadyWithMessage:(id)arg1;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)currentRecordingViewControllerRecordingDidEnd:(id)arg1;
- (void)currentRecordingViewController:(id)arg1 didDeterminteAvailability:(BOOL)arg2;
- (void)dismissLockscreenInterface;
- (void)presentLockscreenInterfaceWithBackgroundColor:(id)arg1 waveformForegroundColor:(id)arg2;
- (void)setScreenUpdatesDisabled:(BOOL)arg1;
- (void)insertRemoteViewController:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (BOOL)shouldAutomaticallyForwardRotationMethods;
- (BOOL)shouldAutomaticallyForwardAppearanceMethods;
- (id)initWithDelegate:(id)arg1;

@end

