//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <HomeSharing/HSResponse.h>

@class NSArray;

@interface HSBulkCloudLyricsInfoResponse : HSResponse
{
    NSArray *lyricsInfoDictionaries;
}

@property(copy, nonatomic) NSArray *lyricsInfoDictionaries; // @synthesize lyricsInfoDictionaries;
- (void).cxx_destruct;
- (void)dealloc;

@end

