/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "MCProfileConnectionObserver-Protocol.h"

@interface _MPRadioStaticProfileConnectionObserver : NSObject <MCProfileConnectionObserver>
{
    _Bool _isProfileExplicitContentRestricted;
}

@property(readonly, nonatomic) _Bool isProfileExplicitContentRestricted; // @synthesize isProfileExplicitContentRestricted=_isProfileExplicitContentRestricted;
- (void)profileConnectionDidReceiveRestrictionChangedNotification:(id)arg1 userInfo:(id)arg2;
- (void)profileConnectionDidReceiveEffectiveSettingsChangedNotification:(id)arg1 userInfo:(id)arg2;
- (void)dealloc;
- (id)init;

@end

