/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>;

@interface MPMediaDownloadObserver : NSObject
{
    id _progressHandler;
    NSObject<OS_dispatch_queue> *_queue;
    BOOL _hasPendingProgressHandlerExecution;
    BOOL _invalidated;
    long long _pid;
}

+ (id)sharedITunesStoreDownloadManager;
+ (id)newObserverForRadioTrack:(id)arg1;
+ (id)newObserverForMediaCollection:(id)arg1;
+ (id)newObserverForMediaItem:(id)arg1;
+ (id)newObserverForMediaItemPersistentID:(unsigned long long)arg1 isPendingSync:(BOOL)arg2 storeID:(long long)arg3;
@property(readonly, nonatomic) long long persistentID; // @synthesize persistentID=_pid;
- (void).cxx_destruct;
@property(readonly, nonatomic) double rawDownloadTotal;
@property(readonly, nonatomic) double rawDownloadProgress;
@property(readonly, nonatomic, getter=isPurchasing) BOOL purchasing;
- (void)invalidate;
- (void)_onQueue_invalidate;
@property(copy) id progressHandler;
@property(readonly, getter=isRestoreDownload) BOOL restoreDownload;
- (void)cancelDownload;
@property(readonly) BOOL canCancel;
@property(readonly, getter=isCurrentlyPlayable) BOOL currentlyPlayable;
@property(readonly) double downloadProgress;
- (void)_onQueue_setShouldFireProgressHandler;
- (void)dealloc;
- (id)init;

@end

