//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <iWorkImport/TSCHChartLayoutItem.h>

__attribute__((visibility("hidden")))
@interface TSCHChartAxisTickMarksLayoutItem : TSCHChartLayoutItem
{
}

- (struct CGAffineTransform)transformForRenderingOutElementSize:(struct CGSize *)arg1 outClipRect:(struct CGRect *)arg2;
- (struct CGRect)calcDrawingRect;
- (struct CGRect)p_effectiveRootedLayoutRect;
- (struct CGSize)calcMinSize;
- (int)location;
@property(readonly, nonatomic) float minorTickmarkLength;
@property(readonly, nonatomic) float majorTickmarkLength;
- (id)initWithParent:(id)arg1;

@end

