//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class APSCourier;

@protocol APSCourierDelegate <NSObject>
- (void)shouldRunDidChange:(APSCourier *)arg1;
- (void)courierConnectionStatusDidChange:(APSCourier *)arg1;
- (void)courierHasNoConnections:(APSCourier *)arg1;
@end

