//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

__attribute__((visibility("hidden")))
@interface TSPPasteboard : NSObject
{
    id _pasteboard;
}

+ (id)pasteboardWithPasteboard:(id)arg1;
+ (id)pasteboardWithUniqueName;
+ (id)pasteboardWithName:(id)arg1 create:(BOOL)arg2;
+ (id)generalPasteboard;
+ (Class)pasteboardClass;
+ (id)activePasteboardForName:(id)arg1;
+ (id)activePasteboards;
+ (id)activePasteboardsQueue;
+ (id)stylePasteboard;
- (void).cxx_destruct;
- (id)description;
- (oneway void)invalidate;
@property(readonly, nonatomic) BOOL isSmartCopy;
- (BOOL)containsImportableTextTypes;
- (BOOL)containsImportableRichTextTypes;
- (BOOL)containsNativePasteboardTypes;
- (id)importablePlainTextTypes;
- (id)importableImageTypes;
- (id)importableRichTextTypes;
- (int)clearContents;
@property(readonly, nonatomic) int changeCount;
@property(readonly, nonatomic) NSString *name;
- (id)valuesForPasteboardType:(id)arg1 inItemSet:(id)arg2;
- (id)dataForPasteboardType:(id)arg1 inItemSet:(id)arg2;
- (id)pasteboardTypesForItemSet:(id)arg1;
- (void)addData:(id)arg1 forPasteboardType:(id)arg2;
- (void)addItems:(id)arg1 isSmartCopy:(BOOL)arg2;
- (void)addItems:(id)arg1;
- (void)performAsynchronousWriteUsingBlock:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) int numberOfItems;
- (id)valueForPasteboardType:(id)arg1;
- (id)dataForPasteboardType:(id)arg1;
- (BOOL)containsAnyPasteboardTypeInArray:(id)arg1;
- (BOOL)containsPasteboardTypes:(id)arg1;
- (id)pasteboardTypes;
@property(readonly, nonatomic) NSArray *URLs;
@property(readonly, nonatomic) NSArray *richTextStrings;
@property(readonly, nonatomic) NSArray *strings;
@property(copy, nonatomic) NSString *string;
- (id)initWithNativePasteboard:(id)arg1;
- (id)initWithUniquePasteboardName;
- (id)initWithPasteboardName:(id)arg1 create:(BOOL)arg2;
- (id)initWithGeneralPasteboard;
- (BOOL)fromIWorkSageDataSource;
- (BOOL)fromExcelDataSource;

@end

