/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class ICCameraDevice, ICCameraFolder, NSDate, NSDictionary, NSMutableDictionary, NSString;

@interface ICCameraItem : NSObject
{
    void *_itemProperties;
}

- (id)initWithName:(id)arg1 parentFolder:(id)arg2 device:(id)arg3;
- (void)dealloc;
- (void)finalize;
- (id)valueForUndefinedKey:(id)arg1;
@property(readonly) ICCameraDevice *device;
@property(readonly) ICCameraFolder *parentFolder;
@property(readonly) NSString *name;
@property(getter=isLocked) BOOL locked;
@property(readonly) NSString *UTI;
- (void)setUTI:(id)arg1;
@property(readonly) NSDate *creationDate;
- (void)setCreationDate:(id)arg1;
@property(readonly) NSDate *modificationDate;
- (void)setModificationDate:(id)arg1;
@property(readonly) BOOL hasThumbnail;
@property(readonly) struct CGImage *thumbnail;
@property(readonly) BOOL hasMetadata;
@property(readonly) NSDictionary *metadata;
- (void)requestThumbnail;
- (void)requestMetadata;
- (void)flushThumbnailCache;
- (void)flushMetadataCache;
@property(readonly) NSMutableDictionary *userData;
- (void)appendToPath:(id)arg1;
@property(readonly) NSString *fileSystemPath;
- (id)description;

@end

