//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIActivityIndicatorView;

__attribute__((visibility("hidden")))
@interface EKEventAttachmentCell : UITableViewCell
{
    UIActivityIndicatorView *_activityIndicator;
}

- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)showSpinner:(BOOL)arg1;
- (void)setAttachment:(id)arg1;
- (id)_iconForDocumentProxy:(id)arg1;

@end

