/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface WBTableCellStyleProperties : NSObject
{
}

+ (void)write:(id)arg1 to:(struct WrdTableProperties *)arg2;
+ (void)readFrom:(struct WrdTableProperties *)arg1 properties:(id)arg2;

@end

