/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class EDReference, EDTable;

@interface EFTableData : NSObject
{
    struct EFRefTok mRefTok;
    EDTable *mTable;
    EDReference *mReference;
    int mMakeups;
}

- (id).cxx_construct;
- (void)makeup:(id)arg1 with:(int)arg2;
- (id)reference;
- (id)table;
- (unsigned short *)ptgData;
- (const struct EFRefTok *)refTok;
- (void)dealloc;
- (id)initWith:(struct EFStrTok *)arg1;

@end

