//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"
#import "NSSecureCoding.h"

@class NSCalendar, NSDate, NSTimeZone;

@interface NSDateComponents : NSObject <NSCopying, NSSecureCoding>
{
}

+ (BOOL)supportsSecureCoding;
+ (id)allocWithZone:(struct _NSZone *)arg1;
- (id)description;
- (BOOL)isValidDateInCalendar:(id)arg1;
@property(readonly, getter=isValidDate) BOOL validDate;
- (int)valueForComponent:(unsigned int)arg1;
- (void)setValue:(int)arg1 forComponent:(unsigned int)arg2;
@property(readonly, copy) NSDate *date;
@property(getter=isLeapMonth) BOOL leapMonth;
@property int yearForWeekOfYear;
@property int weekOfMonth;
@property int weekOfYear;
@property int nanosecond;
@property int quarter;
@property int weekdayOrdinal;
@property int weekday;
- (void)setWeek:(int)arg1;
@property int second;
@property int minute;
@property int hour;
@property int day;
@property int month;
@property int year;
@property int era;
@property(copy) NSTimeZone *timeZone;
@property(copy) NSCalendar *calendar;
- (BOOL)isLeapMonthSet;
- (int)week;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (BOOL)isEqual:(id)arg1;
- (unsigned int)hash;
- (void)dealloc;
- (id)init;

@end

