//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "CNFAudioDeviceControllerProtocol.h"
#import "CNFDisplayControllerDelegate.h"
#import "TUAudioPlayerDelegateProtocol.h"
#import "UIApplicationDelegate.h"

@class AVController, CNFAudioDeviceController, CNFDisplayController, NSObject<CNFCallViewControllerDelegate>, NSURL, TUAudioPlayer, UIWindow;

@interface CNFCallViewController : UIViewController <TUAudioPlayerDelegateProtocol, UIApplicationDelegate, CNFDisplayControllerDelegate, CNFAudioDeviceControllerProtocol>
{
    NSObject<CNFCallViewControllerDelegate> *_delegate;
    CNFDisplayController *_displayController;
    AVController *_avController;
    CNFAudioDeviceController *_deviceController;
    BOOL _isOutgoingInvitation;
    BOOL _initialMuteState;
    BOOL _faceTimeEndedWhileSoundPlaying;
    NSURL *_originationURL;
    TUAudioPlayer *_player;
}

@property(retain, nonatomic) NSURL *originationURL; // @synthesize originationURL=_originationURL;
@property(nonatomic) BOOL initialMuteState; // @synthesize initialMuteState=_initialMuteState;
@property(nonatomic) BOOL isOutgoingInvitation; // @synthesize isOutgoingInvitation=_isOutgoingInvitation;
@property(nonatomic) NSObject<CNFCallViewControllerDelegate> *delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) CNFAudioDeviceController *deviceController; // @synthesize deviceController=_deviceController;
@property(retain, nonatomic) CNFDisplayController *displayController; // @synthesize displayController=_displayController;
- (void)_forceAudioCompletion;
- (void)audioPlayerDidStopPlaying:(id)arg1;
- (void)audioDeviceControllerAudioRoutesChanged:(id)arg1;
- (BOOL)shouldDisableEdgeClip;
- (void)resetToFullScreenPreview;
- (void)returnToFullScreenPreviewWithAnimations:(CDUnknownBlockType)arg1 completion:(CDUnknownBlockType)arg2;
- (void)animateOutWithAnimations:(CDUnknownBlockType)arg1 completion:(CDUnknownBlockType)arg2;
- (void)setIsSendingVideo:(BOOL)arg1;
- (void)stopPreview;
- (void)startPreview;
- (void)startFaceTimeWithURL:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)_stopSounds;
- (void)_playOutgoingRingSound;
- (void)_delayedPlayOutgoingRingSound;
- (BOOL)_endAudioInterruption;
- (void)conferenceDisplayControllerEndedWhileSuspending:(id)arg1;
- (BOOL)auxiliaryAudioRoutesAvailable;
- (void)conferenceDisplayController:(id)arg1 cameraToggleWithReason:(unsigned int)arg2;
- (void)conferenceDisplayController:(id)arg1 muteConferenceWithReason:(unsigned int)arg2;
- (void)conferenceDisplayController:(id)arg1 endWithReason:(unsigned int)arg2;
- (void)conferenceDisplayController:(id)arg1 didFinishAnimatingCallEndWithReason:(unsigned int)arg2;
- (void)conferenceDisplayController:(id)arg1 cancelCallFailureRecoveryWithReason:(unsigned int)arg2;
- (void)conferenceDisplayController:(id)arg1 retryVideoConferenceInvitationWithReason:(unsigned int)arg2;
- (void)conferenceDisplayController:(id)arg1 endCallWithReason:(unsigned int)arg2;
- (id)audioDeviceController;
- (void)_handleDismissConference:(id)arg1;
- (void)_handleFirstRemoteFrame:(id)arg1;
- (void)_handleInvitationSent:(id)arg1;
- (void)_handleStateChanged:(id)arg1;
- (void)_handleConferenceConnected:(id)arg1;
- (void)_handleConferenceConnecting:(id)arg1;
- (void)_gracefullyTerminateAndReturnToLastApp;
- (void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (void)updateViewControllerForOrientation:(int)arg1;
- (void)resumeFromCallWaitingAnimated:(BOOL)arg1;
- (void)prepareForCallWaitingAnimated:(BOOL)arg1;
- (BOOL)isShowingCallWaiting;
- (void)animateShowUnlocked;
- (void)showLockedAnimated:(BOOL)arg1 contactImage:(id)arg2 lockScreenImageView:(id)arg3 withCompletion:(CDUnknownBlockType)arg4;
- (void)didFinishLocking;
- (BOOL)isShowingLock;
- (BOOL)shouldHideStatusBar;
- (BOOL)isShowingFaceTimeUI;
- (BOOL)isInPhoneCall;
- (void)animateFromVoiceControlWithName:(id)arg1 andSubtitle:(id)arg2;
- (void)showAcceptCallBarsAnimated:(BOOL)arg1 callBarsOffscreen:(BOOL)arg2 wasLocked:(BOOL)arg3 wasCallWaiting:(BOOL)arg4;
- (void)showCallBarsAnimated:(BOOL)arg1;
- (void)_muteConference:(BOOL)arg1;
- (id)newDisplayController;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidUnload;
- (void)loadView;
- (BOOL)automaticallyForwardAppearanceAndRotationMethodsToChildViewControllers;
- (void)dealloc;
- (id)initWithDelegate:(id)arg1;

// Remaining properties
@property(retain, nonatomic) UIWindow *window;

@end

