//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DAActionConsumer.h"

@class NSArray;

@protocol DAMailboxFetchSearchResultConsumer <DAActionConsumer>
- (void)searchResultFetchedWithResponses:(NSArray *)arg1;
@end

