//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, RCComposition;

@interface _RCCompositionUndoItem : NSObject
{
    RCComposition *_composition;
    NSString *_reasonAccessTokenName;
}

@property(nonatomic) NSString *reasonAccessTokenName; // @synthesize reasonAccessTokenName=_reasonAccessTokenName;
@property(copy, nonatomic) RCComposition *composition; // @synthesize composition=_composition;
- (void).cxx_destruct;

@end

